### ISSUE TITLE
Brief- oder Buchgrundschuld in API ausgeben

### ISSUE THREAD

**Issue by ollio** [europace/baufismart-antraege-api#10]
Bei den Grundschulden bzw. bestehenden Darlehen zum Objekt kann in der GUI angegeben werden, ob es sich um eine Brief- oder Buchgrundschuld handelt. Im REST-Service gibt es dafür jedoch kein Element. Ist das noch vorgesehen oder bleibt das so? Zu dem Darlehen kann außerdem angegeben werden, ob es im Rahmen der Finanzierung abzulösen ist oder nicht. Dafür gibt es derzeit auch kein Element im REST-Service. Soll diese Info aus dem Element "abzuloesendeRestschuld" abgeleitet werden, wenn der Wert > 0 ist? Derzeit kommt darin aber offenbar immer "null" mit.

**Comment by caspii** [comment]
Beides sollte über den REST Service ausgegeben werden.
