### ISSUE TITLE
Kommentare an Darlehensgeber / Herausgeber / Produktanbieter Feldern verbessern

### ISSUE THREAD

**Issue by marcodischinger** [europace/baufismart-antraege-api#104]
**Is your feature request related to a problem? Please describe.**
In der GUI kann man bei der Pflege von Produktanbietern auch einen Freitext erfassen.
Über die Anträge-API wird dieser Freitext im Feld Firmierung übertragen.
Dazu wird offenbar ein Produktanbieter "erfunden" und als wrappendes Element benutzt.

**Describe the solution you'd like**
Mein Vorschlag ist diese Felder in der API im Kommentar um dieses Verhalten zu ergänzen.
So etwas wie: "Als Freitext erfasste Produktanbieter werden im Feld Firmierung des Produktanbieter Typs geliefert. Alle weiteren Felder sind leer"

**Describe alternatives you've considered**
keine

**Additional context**
![image](https://user-images.githubusercontent.com/38218598/91282603-d64b0d00-e789-11ea-910c-92c8285543a1.png)
![image (1)](https://user-images.githubusercontent.com/38218598/91282625-da772a80-e789-11ea-98e7-095c4f2a6aac.png)

**Comment by marcodischinger** [comment]
Noch besser wäre ein zusätzliches Feld "darlehensGeberFreitext", dass nur gefüllt ist, wenn kein Produktanbieter aus dem Dropdown gewählt wurde. Gleichzeitig wäre dann das Feld "darlehensGeber" null

**Comment by AndreKeil** [comment]
Schließung des Issues

Eine Anpassung der Antraege-API wird nach aktueller Sachlage nicht erfolgen.

Hintergrund: Alle vom Vertrieb erfassten Antragsinformationen können fehlerbehaftet sein, da sie meist auf Eingaben in Freitextfeldern beruhen. Der Mehrwert einer Unterscheidung in der API, ob gerade der `darlehensGeber` aus der BaufiSmart-Dropdown-Liste ausgewählt oder vom Vertrieb selbst erfasst wurde, ist somit gering. Zudem dient diese Information v. a. der Differenzierung, ob es sich bei den Darlehen um eigene oder fremde Vorlasten handelt. Die korrekte Schreibweise ist nachrangig.
