### ISSUE TITLE
PATCH voraussichtlicheBearbeitung funktioniert nicht

### ISSUE THREAD

**Issue by MikeKrueger75** [europace/baufismart-antraege-api#105]
Wie hier beschrieben: https://github.com/europace/baufismart-antraege-api#wie-kann-ich-die-voraussichtliche-bearbeitungsdatum-eines-antrags-setzen
müsste der folgende Request funktionieren, oder?
```
PATCH https://baufismart.api.europace.de/v2/antraege/YM7S18/1/1
body
[
	{ "op": "add", "path": "/voraussichtlicheBearbeitung", "value": "2020-09-03" }
]
```
Es scheinen keine Patch-Operations funktionieren.
Danke für eure Unterstützung.

**Comment by MikeKrueger75** [comment]
Response-Code ist 204

**Comment by schmidthappens** [comment]
Hallo Mike, 

wie kommst du zu der Annahme? In BaufiSmart werden die konkreten Felder übernommen.

![grafik](https://user-images.githubusercontent.com/57909250/91705872-db3f0080-eb7d-11ea-9944-117ee3d7bfe0.png)

Der Response-Code `204` gibt an, dass die Anfrage erfolgreich verarbeitet wurde, jedoch keine Antwort zurückliefert. Grund ist hier, dass auch keine Antwort erfolgen soll, damit wir die Trennung von lesenden und schreibenden Zugriff haben.

Ich hoffe ich konnte Dir helfen?
Martin

**Comment by MikeKrueger75** [comment]
Vielen Dank, Martin
