### ISSUE TITLE
Dokumentation erweitern: Welche OAuth-Berechtigungen werden benötigt?

### ISSUE THREAD

**Issue by jhackel-hypo** [europace/baufismart-antraege-api#108]
In der `README.md`, »Abschnitt Authentifizierung«, beschreibt ihr zwar, dass man ein App-Token zum Zugriff braucht, aber nicht, welche Berechtigungen dieses Token haben muss. Damit ist es praktisch unmöglich, sich selbst im Partner-Management ein passenden Token zu erzeugen.

Beschreibt bitte analog zur [Unterlagen API](https://github.com/europace/unterlagen-api#authentifizierung), welche Berechtigungen  zum API-Zugriff gebraucht werden.

**Comment by FabianStuehler** [comment]
Danke für den Hinweis und haben wir nachgezogen: https://htmlpreview.github.io/?https://raw.githubusercontent.com/hypoport/antraege-auslesen-api/master/Dokumentation/index.html#_oauth2
Bitte den issue dann schließen.

**Comment by jhackel-hypo** [comment]
:+1:
