### ISSUE TITLE
Optimierung der Anzeige Hier: Ablösung von Ratenkrediten vs. vorhandenes Eigenkapital

### ISSUE THREAD

**Issue by matthiassass** [europace/baufismart-antraege-api#115]
Hallo zusammen,

um unsere Erweiterung der API-Live zu nehmen (insbesondere Verträge zurücksenden) benötigen wir zur richtigen Konditionsermittlung eine Angabe darüber, ob (sofern vorhanden) der Kunde Eigenkapital einsetzten möchte um seine bestehenden Verbindlichkeiten abzulösen oder nicht. Sofern EK eingesetzt werden soll benötigen wir auch die Höhe. 

### **Akzeptanzkriterien:**

- Auswahl nur anzeigen sofern folgende Voraussetzungen gegeben sind:
a. Eigenkapital vorhanden
b. Es besteht ein oder mehrere Ratenkredite welche Abgelöst werden sollen

Anbei ein grober Vorschlag für eine Umsetzungsmöglichkeit sowie einige Musterfälle bei denen wir die Konditionen nachträglich anpassen mussten.

VG + Danke für eure Unterstützung
Matthias
![image](https://user-images.githubusercontent.com/58980166/95197390-d4895600-07d9-11eb-9fed-e36913a2a394.png)

**Comment by acodingsquirrel** [comment]
Hallo Matthias,

Eigenkapital wird in BaufiSmart separat zum Ratenkredit erfasst.
Sowohl für den Ratenkredit, als auch für das Eigenkapital kann man angeben, in welcher Höhe man die Punkte ablösen kann.

Also kann man für beide Positionen bestimmen, in welcher Höhe man beide Positionen in die Finanzierung einbringt.
 
Unsere Ergebnisse werden ungenauer, wenn beide Positionen vor dem Klick auf Berechnung durch den Benutzer in Zusammenhang gebracht werden, in der Form „dieser Ratenkredit wird durch diese Eigenkapitalposition zu Betrag x abgelöst“.
Später in der Marktet-Engine berechnen wir die optimale Verwendung von dem Eigenkapital mit Blick auf die gesamte Finanzierung inkl. des Ratenkredits. 
Dabei wird die Anforderung „Eigenkapital für die Auflösung des Ratenkredits aufzubringen“ in der Berechnung bereits heute berücksichtigt.
VG
Christian

**Comment by matthiassass** [comment]
Hallo Christian,

gerade, wenn die Marktet-Engine die optimale Verwendung vom Eigenkapital mit Blick auf die gesamte Finanzierung berechnet, wird dies immer dazu führen, dass das EK für die Ablösung des Ratenkredits verwendet wird. Aus diesem Blickwinkel OK, allerdings wünschen dies in der Regel die Kunden nicht, da das EK in der Regel für die Zahlung der Maklercourtage oder anderer Erwerbsnebenkosten verwendet wird.

Das hat zur Folge, dass wir den Ratenkredit vollständig ablösen und sich dementsprechend andere Konditionen ergeben, als in der optimalen Konstellation.

Vielleicht wäre ein Beispiel hilfreich?

Antrag XR4UBP/1 siehe Anlage (1/2)

![1](https://user-images.githubusercontent.com/58980166/95737797-84ead480-0c88-11eb-9127-d827d0727249.png)
![2](https://user-images.githubusercontent.com/58980166/95737804-874d2e80-0c88-11eb-9879-e83feb217af5.png)


A2 Kondition bedeutet ja nicht nur ein geringerer Zinssatz, sondern auch die Möglichkeit auf die maximale Laufzeit von 180 Monaten. (falsche Rate und ggf. zusätzliche Kosten für den Kunden für das not. Schuldanerkenntnis)
A3 Kondition beinhaltet neben dem höheren Zinssatz eine maximale Laufzeit von 120 Monaten. (falsche Rate und der Kunde hat im schlimmsten Fall bereits die zusätzlichen Ausgaben für das not. Schuldanerkenntnis gehabt)
Außerdem müssen neue Verträge erstellt werden, die der Kunde wieder im Original unterschreiben muss (höherer Aufwand und Zeitverlust für Kunden und VP)

Vielleicht wäre ja auch eine WebEx möglich, um es genau zu erläutern?

**Comment by martinbernhagen** [comment]
Hallo Matthias,

danke für deine Erläuterung und das Beispiel.
Wir erleben, dass Teilablösungen von Ratenkrediten aus Vertriebssicht kaum eine Rolle spielen. Bestehenden Ratenkredite werden also eher ganz umgeschuldet oder gar nicht, sodass sich deine beschriebene Konstellation gar nicht ergibt.

Kannst du uns noch zwei bis drei Fälle schicken, bei denen die beschriebene Konstellation auftrat und neue Verträge erstellt werden mussten? Wir möchten hier gern noch etwas weiter in den Research gehen. Ggfs. hast du auch Daten an der Hand, wie oft ihr bspw. in 2020 diese Konstellation hattet? Das würde uns sehr weiterhelfen.

Gleichzeitig werden wir prüfen, ob die Möglichkeit zur Erfassung von bestehenden Ratenkrediten in der Anzahl von aktuell maximal 3 auf mehr erhöht werden kann/sollte.

Viele Grüße
Martin

**Comment by matthiassass** [comment]
Hallo Martin,

anbei 3 Beispiele inkl. Erläuterung. Diese Beispiele sind nur aus dem Dezember und wir haben nicht den kompletten Dezember durchgesehen:

[cid:image001.png@01D6EDE6.BDC084A0]

[cid:image002.png@01D6EDE6.BDC084A0]

[cid:image003.png@01D6EDE6.BDC084A0]

Wir haben keine Übersicht, bei wie vielen Fällen ein neuer Vertrag aufgrund falscher Kondition im Zusammenhang mit Ablösungen erstellt werden musste.
Wir haben eine Idee, wie wir eventuell an Zahlen kommen könnten, jedoch wäre dies nur mit einem hohen manuellen Aufwand möglich.

Habt Ihr eventuell die Möglichkeit auszuwerten, bei wie vielen Fällen von unserer Seite ein „Gegenangebot“ erstellt wurde?
In der Regel erstellen wir ein „Gegenangebot“, wenn wir die Kondition ändern müssen, um euch und den Vermittler entsprechend zu informieren.

[cid:image004.png@01D6EDE6.BDC084A0]

Gib uns bitte eine Rückmeldung, ob Du noch weitere Informationen benötigst.

VG
Matthias

Mit freundlichen Grüßen
Best regards

Matthias Saß
(CON-B2B)

Hanseatic Bank
Bramfelder Chaussee 101<x-apple-data-detectors://2/0>  .  22177  Hamburg
Tel +49<tel:+49%2040%206000%2096%201201> 40 6000 96 1201<tel:+49%2040%206000%2096%201201>
Mobil +49 172 203 98 66<tel:+49%20172%20203%2098%2066>
matthias.sass@hanseaticbank.de<mailto:matthias.sass@hanseaticbank.de>
www.hanseaticbank.de
_______________________________________________
Hanseatic Bank GmbH & Co KG  .  22177 Hamburg  .  Bramfelder Chaussee 101<x-apple-data-detectors://3/> .  AG Hamburg HRA 68192
Persönlich haftend: Hanseatic Gesellschaft für Bankbeteiligungen mbH.  .  AG Hamburg HRB 12564
Geschäftsführer: Michel Billon, Detlef Zell  .  Beiratsvorsitzender: Giovanni Luca Soma

SAVE PAPER - THINK BEFORE YOU PRINT

Von: Martin Bernhagen <notifications@github.com>
Gesendet: Freitag, 15. Januar 2021 11:13
An: europace/baufismart-antraege-api <baufismart-antraege-api@noreply.github.com>
Cc: Sass, Matthias <Matthias.Sass@hanseaticbank.de>; Author <author@noreply.github.com>
Betreff: Re: [europace/baufismart-antraege-api] Optimierung der Anzeige Hier: Ablösung von Ratenkrediten vs. vorhandenes Eigenkapital (#115)


Hallo Matthias,

danke für deine Erläuterung und das Beispiel.
Wir erleben, dass Teilablösungen von Ratenkrediten aus Vertriebssicht kaum eine Rolle spielen. Bestehenden Ratenkredite werden also eher ganz umgeschuldet oder gar nicht, sodass sich deine beschriebene Konstellation gar nicht ergibt.

Kannst du uns noch zwei bis drei Fälle schicken, bei denen die beschriebene Konstellation auftrat und neue Verträge erstellt werden mussten? Wir möchten hier gern noch etwas weiter in den Research gehen. Ggfs. hast du auch Daten an der Hand, wie oft ihr bspw. in 2020 diese Konstellation hattet? Das würde uns sehr weiterhelfen.

Gleichzeitig werden wir prüfen, ob die Möglichkeit zur Erfassung von bestehenden Ratenkrediten in der Anzahl von aktuell maximal 3 auf mehr erhöht werden kann/sollte.

Viele Grüße
Martin

**Comment by matthiassass** [comment]
Hallo Martin,

kurzer Nachtrag zu meiner gestrigen Mail:

Beim erneuten Lesen der E-Mail ist uns aufgefallen, dass über Teilablösungen gesprochen wird. Das ist nicht unser Thema, uns geht es allein um die Anrechnung des vorhandenen EKs bei Ratenkreditablösungen. Die Kunden wünschen in der Regel die Komplettablösung über die HB und das EK soll anderweitig verwendet werden.

VG
Matthias

Mit freundlichen Grüßen
Best regards

Matthias Saß
(CON-B2B)

Hanseatic Bank
Bramfelder Chaussee 101<x-apple-data-detectors://2/0>  .  22177  Hamburg
Tel +49<tel:+49%2040%206000%2096%201201> 40 6000 96 1201<tel:+49%2040%206000%2096%201201>
Mobil +49 172 203 98 66<tel:+49%20172%20203%2098%2066>
matthias.sass@hanseaticbank.de<mailto:matthias.sass@hanseaticbank.de>
www.hanseaticbank.de
_______________________________________________
Hanseatic Bank GmbH & Co KG  .  22177 Hamburg  .  Bramfelder Chaussee 101<x-apple-data-detectors://3/> .  AG Hamburg HRA 68192
Persönlich haftend: Hanseatic Gesellschaft für Bankbeteiligungen mbH.  .  AG Hamburg HRB 12564
Geschäftsführer: Michel Billon, Detlef Zell  .  Beiratsvorsitzender: Giovanni Luca Soma

SAVE PAPER - THINK BEFORE YOU PRINT

Von: Sass, Matthias
Gesendet: Montag, 18. Januar 2021 22:11
An: 'europace/baufismart-antraege-api' <reply@reply.github.com>; europace/baufismart-antraege-api <baufismart-antraege-api@noreply.github.com>
Cc: Author <author@noreply.github.com>
Betreff: AW: [europace/baufismart-antraege-api] Optimierung der Anzeige Hier: Ablösung von Ratenkrediten vs. vorhandenes Eigenkapital (#115)

Hallo Martin,

anbei 3 Beispiele inkl. Erläuterung. Diese Beispiele sind nur aus dem Dezember und wir haben nicht den kompletten Dezember durchgesehen:

[cid:image001.png@01D6EE35.63797570]

[cid:image002.png@01D6EE35.63797570]

[cid:image003.png@01D6EE35.63797570]

Wir haben keine Übersicht, bei wie vielen Fällen ein neuer Vertrag aufgrund falscher Kondition im Zusammenhang mit Ablösungen erstellt werden musste.
Wir haben eine Idee, wie wir eventuell an Zahlen kommen könnten, jedoch wäre dies nur mit einem hohen manuellen Aufwand möglich.

Habt Ihr eventuell die Möglichkeit auszuwerten, bei wie vielen Fällen von unserer Seite ein „Gegenangebot“ erstellt wurde?
In der Regel erstellen wir ein „Gegenangebot“, wenn wir die Kondition ändern müssen, um euch und den Vermittler entsprechend zu informieren.

[cid:image004.png@01D6EE35.63797570]

Gib uns bitte eine Rückmeldung, ob Du noch weitere Informationen benötigst.

VG
Matthias

Mit freundlichen Grüßen
Best regards

Matthias Saß
(CON-B2B)

Hanseatic Bank
Bramfelder Chaussee 101<x-apple-data-detectors://2/0>  .  22177  Hamburg
Tel +49<tel:+49%2040%206000%2096%201201> 40 6000 96 1201<tel:+49%2040%206000%2096%201201>
Mobil +49 172 203 98 66<tel:+49%20172%20203%2098%2066>
matthias.sass@hanseaticbank.de<mailto:matthias.sass@hanseaticbank.de>
www.hanseaticbank.de
_______________________________________________
Hanseatic Bank GmbH & Co KG  .  22177 Hamburg  .  Bramfelder Chaussee 101<x-apple-data-detectors://3/> .  AG Hamburg HRA 68192
Persönlich haftend: Hanseatic Gesellschaft für Bankbeteiligungen mbH.  .  AG Hamburg HRB 12564
Geschäftsführer: Michel Billon, Detlef Zell  .  Beiratsvorsitzender: Giovanni Luca Soma

SAVE PAPER - THINK BEFORE YOU PRINT

Von: Martin Bernhagen <notifications@github.com>
Gesendet: Freitag, 15. Januar 2021 11:13
An: europace/baufismart-antraege-api <baufismart-antraege-api@noreply.github.com>
Cc: Sass, Matthias <Matthias.Sass@hanseaticbank.de>; Author <author@noreply.github.com>
Betreff: Re: [europace/baufismart-antraege-api] Optimierung der Anzeige Hier: Ablösung von Ratenkrediten vs. vorhandenes Eigenkapital (#115)


Hallo Matthias,

danke für deine Erläuterung und das Beispiel.
Wir erleben, dass Teilablösungen von Ratenkrediten aus Vertriebssicht kaum eine Rolle spielen. Bestehenden Ratenkredite werden also eher ganz umgeschuldet oder gar nicht, sodass sich deine beschriebene Konstellation gar nicht ergibt.

Kannst du uns noch zwei bis drei Fälle schicken, bei denen die beschriebene Konstellation auftrat und neue Verträge erstellt werden mussten? Wir möchten hier gern noch etwas weiter in den Research gehen. Ggfs. hast du auch Daten an der Hand, wie oft ihr bspw. in 2020 diese Konstellation hattet? Das würde uns sehr weiterhelfen.

Gleichzeitig werden wir prüfen, ob die Möglichkeit zur Erfassung von bestehenden Ratenkrediten in der Anzahl von aktuell maximal 3 auf mehr erhöht werden kann/sollte.

Viele Grüße
Martin

**Comment by martinbernhagen** [comment]
Hallo Matthias,

entschuldige die verzögerte Rückmeldung. 

Kannst du zu den Beispielvorgängen nochmal die Vorgangsnummer schicken? Die Screenshots sind in deinem Post oben nicht sichtbar.

Danke für deine Erläuterung bzgl. der Teilablösungen. Das bringt uns schon ein Stück weiter und wir haben hier den gleichen Nenner.

Um eine Auswertung zu den erstellten Gegenangeboten kümmern wir uns. Sobald ich hier Infos für euch habe, melde ich mich.

Viele Grüße
Martin

**Comment by matthiassass** [comment]
Hallo Martin,

hier die entsprechenden Vorgangsnummern:

GZ4QRQ
X08KPL
VP9NZM

VG
Matthias

Mit freundlichen Grüßen
Best regards

Matthias Saß
(CON-B2B)

Hanseatic Bank
Bramfelder Chaussee 101<x-apple-data-detectors://2/0>  .  22177  Hamburg
Tel +49<tel:+49%2040%206000%2096%201201> 40 6000 96 1201<tel:+49%2040%206000%2096%201201>
Mobil +49 172 203 98 66<tel:+49%20172%20203%2098%2066>
matthias.sass@hanseaticbank.de<mailto:matthias.sass@hanseaticbank.de>
www.hanseaticbank.de
_______________________________________________
Hanseatic Bank GmbH & Co KG  .  22177 Hamburg  .  Bramfelder Chaussee 101<x-apple-data-detectors://3/> .  AG Hamburg HRA 68192
Persönlich haftend: Hanseatic Gesellschaft für Bankbeteiligungen mbH.  .  AG Hamburg HRB 12564
Geschäftsführer: Michel Billon, Detlef Zell  .  Beiratsvorsitzender: Giovanni Luca Soma

SAVE PAPER - THINK BEFORE YOU PRINT

Von: Martin Bernhagen <notifications@github.com>
Gesendet: Mittwoch, 3. Februar 2021 14:36
An: europace/baufismart-antraege-api <baufismart-antraege-api@noreply.github.com>
Cc: Sass, Matthias <Matthias.Sass@hanseaticbank.de>; Author <author@noreply.github.com>
Betreff: Re: [europace/baufismart-antraege-api] Optimierung der Anzeige Hier: Ablösung von Ratenkrediten vs. vorhandenes Eigenkapital (#115)


Hallo Matthias,

noch ein Nachtrag: Die Gegenangebotsquote bei der Hanseatic betrug 4,48% in 2020. Die Gegenangebotsquote drückt aus, in wie viel Prozent aller Vorgänge ein Gegenangebot durch den PA erzeugt wurde.

Im Verhältnis zum Gesamtgeschäft ist das also ein sehr niedriger Wert, in dem die Konditionen "korrigiert" werden müssen.

Viele Grüße
Martin

**Comment by martinbernhagen** [comment]
Hallo Matthias,

entschuldige die späte Rückmeldung. Nachdem du mit Nicole Buikis und Gerald Steiner im Austausch warst und wir heute nochmal zu dem Thema gesprochen haben, werden wir prüfen, inwiefern die Logik der Market Engine angepasst werden kann, um keinen automatischen EK-Einsatz mehr für Privatdarlehen vorzunehmen, sondern, wie von dir beschrieben, zunächst die Nebenkosten durch EK berücksichtigen.

Sobald wir hier Erkenntnisse haben, kommen wir auf dich zu.

Viele Grüße
Martin

**Comment by AndreKeil** [comment]
Schließung des Issues

Hintergrund: Thema ist keines, welches diesen Service (Antraege-API) berührt.

@matthiassass Ich gehe davon aus, dass sich das Thema bereits erledigte und lediglich die Schließung des Issues hier versäumt wurde. Falls ich mich irre, gehe gern nochmal auf Nicole Buikis zu!
