### ISSUE TITLE
Grundbuchangaben.Amtsgericht

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-antraege-api#122]
Hallo,
ich erhalte die Angabe "Amtsgericht" unter Grundbuchangaben nicht. Ist da etwas bekannt?
Meine Anfrage: https://baufismart.api.europace.de/v2/vorgaenge/JT4BZ6
In den Releases habe ich gesehen, dass dies in 2.25 geändert wurde. Dort wurde auch die bestehendeDarlehen.Grundbuchart aufgenommen. Diese erhalte ich z.B. bei Y82PNT...
Kann mir das gerade nicht erklären.

**Comment by paleise** [comment]
Meine Anfrage: https://baufismart.api.europace.de/v2/vorgaenge/JT4BZ6

**Comment by FabianStuehler** [comment]
Das Amtsgericht wird an der Antrag API ausgeliefert: https://baufismart.api.europace.de/v2/antraege/JT4BZ6/2/1
Dieses Feld wird noch nicht bei der Vorgang API ausgegeben: https://github.com/europace/baufismart-vorgaenge-api.
