### ISSUE TITLE
Feld umbenennen: bandUndBlatt

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#13]
Im Frontend heißt ein Feld für Grundbuchangaben "Blatt (Band: optional)"

In der API heisst es `bandUndBlatt`was fragen aufwirft. Besser wäre es `blattUndBand` zu nennen

**Comment by u00kram** [comment]
Auch hier meine Frage - wie ist der aktuelle Stand der Umsetzung? Danke.

**Comment by caspii** [comment]
Das machen wir im nächsten Release der API

**Comment by caspii** [comment]
Sorry, aus versehen geschlossen

**Comment by FabianStuehler** [comment]
Werden wir für die v3 vorsehen
