### ISSUE TITLE
Fehlende Felder

### ISSUE THREAD

**Issue by paleise** [europace/baufismart-antraege-api#131]
Wir haben weiterhin und vermehrt viele Anfragen/Support wegen fehlenden Feldern/Werte. Durch die Einführung der Kundenangaben API, welche jetzt fast alle Felder berücksichtigt, kommt es zu vielen Unterschieden, wenn der Vorgang wieder aus Europace über diese API "zurückgeholt" wird (Amtsgericht, Kommentar bei Anschlussfinanzierung zusätzliches Kapital). Ist hier bald mit Ergänzungen zu rechnen?

**Comment by AndreKeil** [comment]
Hallo @paleise,

leider erfasse ich das eigentliche Problem noch nicht. Wenn ihr uns über die Kundenangaben-API die Informationen sendet, so sind sie doch bereits in Eurem System vorhanden?! Worin läge der Mehrwert, diese bekannten Informationen redundant über die Anträge-API wieder an Euch zurückzuspielen?

Im Kontext eines "schlanken API-Design" würden wir gern den Use Case verstehen. Dieser Chat ist jedoch ungeeignet... Geht bitte gern auf Euren Europace-Betreuer zu.

Es grüßt Dich


André Keil

**Comment by paleise** [comment]
Hallo Andre,
mh da bin ich jetzt nicht ganz einverstanden. Also wir holen uns nun ab und zu einmal Vorgänge von Europace in unser eigenes System, und da wäre es schön, wenn ALLE Felder abgerufen werden könnten. Leider fehlen ein paar.
Was ich an deiner Antwort nicht ganz verstehe ist, dass ich aus vorigen Informationen von euch mitgeteilt bekommen habe, dass ihr das wisst und demnächst behebt. Wäre ja auch schön, wenn die Kundenangaben API die gleichen Felder wie die Anträge API berücksichtigt. 
Gruß
Peter Artelt

**Comment by AndreKeil** [comment]
Hallo Peter,

die Intension der Anträge-API ist nicht die technische 1-zu-1-Abbildung aller Erfassungsfelder unseres Frontends "BaufiSmart" bzw. eine Widerspiegelung der Kundenangaben-API. Vielmehr dient sie dazu, dass Produktanbieter Anträge für die Kreditentscheidung in ihre Systeme überführen können.

Gern prüfen wir die Erfordernis von Erweiterungen, falls die derzeitige Ausbaustufe der API diesen Zweck (noch) nicht erfüllt. Hierzu wollen wir die genaue Problemstellung verstehen - auch um die Prioritäten einschätzen zu können. 

Ich möchte daher die Einladung erneuern, mit Eurem Europace-Betreuer in den Dialog zu gehen, um im gemeinsamen Gespräch Lösungen zu erarbeiten.

Es grüßt Dich


André Keil
