### ISSUE TITLE
Übertrag der Branche

### ISSUE THREAD

**Issue by matthiassass** [europace/baufismart-antraege-api#135]
Als Produktanbieter möchten wir, sofern die Angaben im Antrag gemacht werden, auch die Branche übermittelt bekommen. Dieses Feld existiert bereits in der API ist jedoch nur für einige Produktanbieter freigeschaltet. 

Wir würden uns freuen, wenn Ihr das Feld auch an uns übertragen könntet. 

VG
Matthias

**Comment by AndreKeil** [comment]
Hallo Matthias,

die Branche wird nur bei einigen wenigen Produktanbietern in den anbieterspezifischen Zusatzangaben in BaufiSmart abgefragt (sprich: Die möglichen Ausprägungen variieren zwischen diesen [siehe auch "Erlaubte Werte" auf https://europace.github.io/baufismart-antraege-api/docs/index.html]). Hintergrund ist, dass bei den Partnern die Branche in die Angebotsprüfung bzw. in das Pricing einfließt und zu einer besseren Produktabbildung auf Europace führt. Entsprechend muss diese Information auch im Antrag enthalten sein.

Damit kann sie aber auch nicht einfach "gestreut" werden. Im Zweifel erhieltet ihr keine oder mehrere abweichende Branchen - je nach Erfassung durch den Vertrieb in den anbieterspezifischen Zusatzangaben.

Sofern wir in BaufiSmart ein allgemeingültiges Feld "Branche" implementier(t)en, übermittel(te)n wir diese Information selbstverständlich auch in der Anträge-API allen Partnern. Aktuell steht dieses Thema aber nicht im Fokus.

Es grüßt Dich


André Keil

**Comment by matthiassass** [comment]
Hallo @AndreKeil ,

danke für die Infos. Dann kann das Ticket hier erstmal zu und wir warten bis diese Funktionalität grundsätzlich zur Verfügung steht. 

VG
Matthias
