### ISSUE TITLE
Fehler bei Antragsabholung / Testantrag F71659/17 

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#14]
Guten Tag zusammen,
wir versuchen den Testantrag F71659/17 (Vorhaben ASF) abzuholen und bekommen einen leeren Eintrag - also keine Daten zur Übertragung. Wir testen gerade alle Vorhabensarten in verschiedenen Konstellation für unser nächstes Release.
Wo kann das Problem liegen - es ist dringend?!
Technische Fragen bitte an Andreas.tauber@sdv-it.de oder 0911 9291 2532
Vielen Dank. 

Der Aufruf beinhaltet die TraceID: SDV-IT_F71659_17 

Fehler: 
```
10:25:46 vorm.: class Antraege {
    antraege: [class Antrag {
        angebot: null
        ansprechpartner: null
        antragsNummer: F71659/17
        antragsReferenz: null
        beratung: null
        datenKontext: TEST_MODUS
        dokumente: null
        kreditSachbearbeiter: null
        produktAnbieter: null
        status: null
        vermittler: null
        voraussichtlicheBearbeitung: null
        vorgangsReferenz: null
        zeitpunktDerAnnahme: 2018-10-26T09:36:48.876+02:00
        zugrundeliegendeDaten: null
        links: class Links {
            self: class Link {
                href: https://baufismart.api.europace.de/v2/antraege/F71659/17
                type: null
            }
        }
    }]
    links: class PaginationLinks {
        next: null
        prev: null
        self: class Link {
            href: https://baufismart.api.europace.de/v2/antraege/?datenKontext=TEST_MODUS&angenommenNach=2018-10-26T09:35:08.360%2B02:00&sort=absteigend&page=0&limit=1000
            type: null
        }
    }
} 
```

**Comment by u00kram** [comment]
Andreas Tauber ergänzt:
Die zugrundeliegenden Daten zum Antrag sind leer. Der Antrag ist  da, aber ohne Daten. Beim Lesen aus der Http Response Body erhalten wir trotzdem eine leere Liste.

**Comment by caspii** [comment]
@u00kram hat denn der Abruf der anderen 16 Anträge funktioniert?

**Comment by caspii** [comment]
@u00kram wir sind in die Analyse gegangen und haben festgestellt, dass die API Fehler aufwirft, wenn mehr als 10 Anträge in einem Vorgang sind. Das werden wir diese Woche beheben.

Bis dahin sollten nur Anträge aus Vorgängen mit insgesamt <=10 Anträgen abgerufen werden.

**Comment by u00kram** [comment]
Danke - habe ich zur Kenntnis genommen und werde den Hinweis derzeit beachten.

**Comment by caspii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [IST Antraege API: Antrag kann nicht abgeholt werden](https://trello.com/c/kiIkLkm4/1454-ist-antraege-api-antrag-kann-nicht-abgeholt-werden)

**Comment by caspii** [comment]
Test kommentar

**Comment by gruenewa** [comment]
@u00kram Der Fehler ist jetzt behoben. Vielen Dank nochmal für den Hinweis.

**Comment by K0ne** [comment]
wurde gefixt

**Comment by u00kram** [comment]
Test mit F71659/19 erfolgreich.
