### ISSUE TITLE
Dokumenten_API: Rückfrage zum Abruf der Metadaten

### ISSUE THREAD

**Issue by DavideVaccalluzzo** [europace/baufismart-antraege-api#157]
Hallo,

wir haben vergangene Woche einen ersten Durchstich zur DokumentenAPI getestet. Beim Abruf der Metadaten haben wir eine frei erfundene Antragsnummer (edsfgdf) mitgegeben. Dennoch haben wir einen erfolgreichen 200-Response bekommen. 

Findet beim Abruf der Metadaten keine Plausibilitätsprüfung bezgl. der Antragsnummer statt? 

Besten Dank vorab für die Unterstützung. 

Davide Vaccalluzzo
im Auftrag der Finanz Informatik

**Comment by AndreKeil** [comment]
Hallo Davide,

so wie ich es verstehe, geht es um die Dokumente-API? Dann ist dies nicht der richtige Channel. 

Bitte formuliere Dein Anliegen noch einmal hier: [](https://github.com/europace/baufismart-dokumente-api/issues). Unsere Kolleg:innen, welche für die Dokumente-API verantwortlich zeichnen, helfen Dir sicher gern weiter.

Es grüßt Dich


André Keil
