### ISSUE TITLE
Query Parameter "angenommenNach" und "angenommenVor" gerade wirkungslos?

### ISSUE THREAD

**Issue by grubermar** [europace/baufismart-antraege-api#160]
Hallo zusammen,

der Aufruf
https://baufismart.api.europace.de/v2/antraege?limit=1000&datenKontext=ECHT_GESCHAEFT&angenommenNach=2022-12-06T00:00:00.01Z&angenommenVor=2022-12-20T09:26:53.01Z

liefert uns seit gestern nicht nur die Anträge der letzten beiden Wochen sondern mehrere tausend.
Wurden die Parameter oder das Format irgendwie angepasst?

Danke!

**Comment by unstko** [comment]
Hallo @grubermar,

vielen Dank für Ihre Anfrage. Wir werden das Problem analysieren und melden uns, sobald wir neue Erkenntnisse dazu haben.

**Comment by unstko** [comment]
Hallo @grubermar,

bitte verwenden Sie drei statt zwei Nachkommastellen bei der Uhrzeit. In Ihrem Beispiel also `2022-12-06T00:00:00.001Z` und `2022-12-20T09:26:53.001Z`.

**Comment by grubermar** [comment]
Hallo @unstko,

vielen Dank, hat funktioniert!
