### ISSUE TITLE
Abruf eines Antrags über API nicht möglich aufgrund Rechte-Konstellation

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#17]
Der Nutzer CEP53 versucht den Antrag E13156/1 per Antrage API abzurufen (GET https://baufismart.api.europace.de/v2/antraege/E13156/2).

IST: Als Antwort kommt 403 Zugriff verweigert
SOLL: Als Antwort kommt der Antrag der Sparda BW (E13156/2/1)

# Hintergrund
Im Antrag gilt die Sparda BW als führender PA für den BHW Baustein
Der Nutzer hat angeblich widersprüchliche Rechte in unterschiedlichen Systemen (BS vs ME vs ..). Kone hat da eine Voranalyse gemacht
Der Nutzer hat eigentlich nicht das Recht, den Teilantrag der BHW zu sehen
Der Nutzer hat das "Entwicklertools" Flag gesetzt und darf deshalb doch auf den Teilantrag der BHW zugreifen.

**Comment by caspii** [comment]
@u00kram Der Antrag ist ein Echtgeschäft Antrag, Nutzer (Plakette "CEP53") hat aber nur Testzugang.

**Comment by u00kram** [comment]
Hallo Herr Wrede, 
unsere Anträge Echt-Geschäft werden nach wie vor - und noch nie anders - mit dem TechnUser u60epap für unsere Produktion mit der PartnerID GPI08 abgeholt.
12.10.18 um 14:00:40 bei Vorgang E13156/1 den Http Status Code 403 in Produktion. 
Wir konnten diesen Http 403 in unserer Entwicklung bzw. Integrationsumgebung mittels dem Testantrag ML8901/6 reproduzieren. Nur hier erfolgte damals der Zugriff auf die AnträgeAPI mittels der PartnerID CEP53. 
Schon seit einiger Zeit werden die Testanträge nur noch mit den TechnUsern für die Testumgebungen u60epai / u60epaa /  u60epas abgeholt.
Fazit: Es kann bei Echt-Geschäft nicht am Nutzer (Plakette "CEP53")  liegen.
Den Testantrag: F71659/18  habe ich vorhin in der Konstellation nochmal abgeschickt. Er ist auf einen Fehler gelaufen. Andreas Tauber kann sich den Fehler erst am Montag anschauen.
Wie schaut es auf Ihrer Seite aus? Abholung durch den User u60epai.
Entweder waren zu viele Anträge das Problem oder der bekannte Fehler 403?
Danke und VG, Manuela Kränz

**Comment by u00kram** [comment]
Danke.
Richtig - das Thema Fehler bei mehr als 10 Anträgen wird im #14 bearbeitet.
Ich hatte nur keine Fehlermeldung zur Hand, deshalb war ich mir nicht sicher.

**Comment by europacesupport** [comment]
Der Fehler müsste behoben sein
