### ISSUE TITLE
Adding new ENUM in darlehensTyp breaks build

### ISSUE THREAD

**Issue by andreasvp** [europace/baufismart-antraege-api#175]
Do you have a hint on how to bypass the errors when building you api with "openapi-generator-maven-plugin" (v6.6.0).

After adding the ENUM to specific darlehnsTyp (Privat, Forward .... etc.) the API don't build due to errors regarding "cannot override getDarlehensTyp() from GegenangebotDarlehen"

Thanks

**Comment by andreasvp** [comment]
Thanks for the response.
With v2.59 you removed the unnecessary types from respective darlehensTyp's (e.g. in ForwardDarlehen). As the ForwardDalehen inherits from “#/definitions/GegenangebotDarlehen” the definition of “darlehensTyp” will be overwriten. 
This leads to an openapi generation error as the java “darlehensTyp” types of “GegenangebotDarlehen” and “ForwardDarlehen” are not compatible.
Do you have a suggestion on a openapi switch to allow generation of the interface?

**Comment by Integer93** [comment]
We do not have any suggestions on working generators. We do not offer support for the generation because there are a lot of generators out there and every user uses a different one.
As of now the documentation reflects the API as intended. The inherited classes only allow one value of the enum. Otherwise it would be a other class.

However if we finde out that that change has broken a lot of generators we would discuss to revert it. Could you provide us with that information? We currently don't have the generation set up and that would take us some time.

**Comment by andreasvp** [comment]
It doesn't build with openapi-generator-maven-plugin(v6.6.0) and swagger-codegen-maven-plugin (v2.4.15).

with 
   ```
....
   <plugin> 
	<groupId>org.openapitools</groupId>
	<artifactId>openapi-generator-maven-plugin</artifactId>
	<version>6.6.0</version>
	<executions>
	  <execution>
		<id>Genopace AntraegeAPI</id>
		<goals>
		  <goal>generate</goal>
		</goals>
		<configuration>
		  <inputSpec>
			${project.basedir}/src/main/resources/api-consumer/GenopaceAntraegeApi.yaml
		  </inputSpec>
		  <generatorName>java</generatorName>
		  <apiPackage>de.genopace.antraege.api</apiPackage>
		  <modelPackage>de.genopace.antraege.model</modelPackage>
		  <generateApis>true</generateApis>
		  <generateModels>true</generateModels>
		  <generateSupportingFiles>true</generateSupportingFiles>
		  <output>${project.build.directory}</output>
		  <configOptions>
			<library>resttemplate</library>
			<invokerPackage>de.genopace.antraege.client
			</invokerPackage>
			<sourceFolder>generated-sources/openapi</sourceFolder>
			<booleanGetterPrefix>get</booleanGetterPrefix>
			<hideGenerationTimestamp>true</hideGenerationTimestamp>
			<interfaceOnly>true</interfaceOnly>
			<openApiNullable>false</openApiNullable>
			<useJakartaEe>true</useJakartaEe>
			<generateClientAsBean>true</generateClientAsBean>
		  </configOptions>
		</configuration>
	  </execution>
	  ...
```

<SNIP>
	```
....
	<plugin>
		<groupId>io.swagger</groupId>
		<artifactId>swagger-codegen-maven-plugin</artifactId>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
				<configuration>
					<inputSpec>${project.basedir}/src/main/resources/services/europace2/europace2-swagger.json
					</inputSpec>
					<language>java</language>
					<modelPackage>
						de.europace2.antragsstrecke.model
					</modelPackage>
					<apiPackage>de.europace2.antragsstrecke
					</apiPackage>
					<invokerPackage>
						de.europace2.antragsstrecke
					</invokerPackage>
					<generateApiTests>false</generateApiTests>
					<generateModelTests>false</generateModelTests>
					<configOptions>
						<sourceFolder>src/gen/java/main</sourceFolder>
						<dateLibrary>java8</dateLibrary>
						<library>resttemplate</library>
						<artifactId>europace-api-client</artifactId>
						<groupId>de.europace.api</groupId>
						<artifactVersion>0.1</artifactVersion>
					</configOptions>
				</configuration>
			</execution>
		</executions>
		...
```

**Comment by Integer93** [comment]
We used 'io.swagger:swagger-codegen:2.4.32' for the generation.
If that version also dosen't work for you will look deeper into it tomorrow.

**Comment by Integer93** [comment]
How can i send you a new version for you to check it? I found a `nospam` email adress from you, but that didn't work.

**Comment by andreasvp** [comment]
I will contact you trough our business channel :-)

**Comment by Integer93** [comment]
Well will roll out a new version that fixes the client generation.

**Comment by andreasvp** [comment]
excellent !
