### ISSUE TITLE
Maximal einzusetzender Betrag im Frontend nicht konsistent mit API Response

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#18]
Hallo Herr Wrede,
warum wird der Maximal einzusetzende Betrag für ein Bank- und Sparguthaben - im Testfall KD9685/3
mit 50000 Euro eingegeben - in der Responsedatei mit maximalAufzuloesenderWert: 7400 übertragen?
Vorher schon bei anderen Testfällen beobachtet. (EG8973/6)
Bei wieder anderen Testfällen wurde der richtige  Maximal einzusetzende Betrag übergeben.
ZB QS6759/3 oder  WF7274/1
Ich teste gerade nochmal für unser Release - deshalb ist eine Erklärung wieder mal dringend.
Danke und VG, Manuela Kränz

**Comment by caspii** [comment]
Der Wert ist korrekt aber es ist zugegebenermaßen verwirrend:
* Im Frontend wird der Maximal *einzusetzender* Betrag eingegeben
* In der API wird der maximal *aufzulösender* Betrag ausgegeben. Dieser hängt von der Finanzierung ab -- es wird der Betrag verwendet, der benötigt wird, so das keine Überfinanzierung entsteht

**Comment by u00kram** [comment]
Danke für die Erklärung. Die Sparda-Banken nutzen dieses Mapping schon und sollten dazu wissend sein. Mir ist es nur durch die umfangreicheren Abnahmetests aufgefallen.
Nun ist es auch mir klar.

**Comment by caspii** [comment]
Ich mache das Ticket wieder auf, denn wir müssen die Felder in einem neuen Release besser benamen

**Comment by u00kram** [comment]
Gute Idee. Danke.

**Comment by caspii** [comment]
Eine weitere Meldung: #8

**Comment by ollio** [comment]
@caspii Ich habe auch ein BS UI Ticket auf gemacht. https://github.com/hypoport/ep2-core/issues/822

**Comment by u00kram** [comment]
Hallo Herr Wrede,
wie schaut es denn mit dem Thema aus? 
Die Bank hat bei den letzten Tests genau dieses Thema beanstandet. Diese Umsetzung fand die SpB BW auch nicht wirklich gut.
Sollte hier nicht der Ursprungswert des Eigenkapitals UND dann der berechnete Wert in den Daten mitgegeben werden - dann können wir mappen, wie es die Bank wünscht. Ist das möglich?
Vielen Dank und VG, Manuela Kränz
