### ISSUE TITLE
Das Feld zeitpunktDerAnnahme fehlt seit 22.11.2023

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-antraege-api#183]
Leider wird das Feld **zeitpunktDerAnnahme** seit dem 22.11.2023 nicht mehr übertragen, insbesondere bei den Abschlussdaten des Falles mit der Europace-ID U44JX4 wird diese Information nicht mehr mit übertragen. 

Ich nutze für das Retrieval der Daten folgende API-URL: https://baufismart.api.europace.de/v2/vorgaenge/{ID}/antraege

**Comment by ic-hv** [comment]
Ok, ich konnte eine Lösung finden:

Vorher war dieses Feld unterhalb von "**angebot**" zu finden, jetzt ist es aber wohl ein Ebene höher gewandert und findet sich nun direkt im Antrag. 

Nichtsdestotrotz wäre es schön, wenn man über eine derartige Anpassung vorher informiert würde! Gibt es hierfür einen Email-Verteiler, wo ich mich eintragen kann?

Danke und herzliche Grüße,
Heiko Vogel

**Comment by ic-hv** [comment]
Hmm, leider entspricht das **zeitpunktDerAnnahme** im Antrag leider nicht dem Zeitpunkt der Annahme des Angebots, demnach ist meine zuvor gepostete Lösung doch keine.

Demnach Europace: Bitte wieder **zeitpunktDerAnnahme** ins Angebot packen! Danke!

**Comment by unstko** [comment]
@ic-hv Wie unter https://europace.github.io/baufismart-antraege-api/docs/index.html#_antrag zu sehen, ist das Feld `zeitpunktDerAnnahme` Teil des Antrags.

Es gab (vor allem in den letzten Tagen) keine Anpassungen an der API, wodurch das Feld an eine andere Stelle verschoben wurde. Meine Recherchen im Code der Anträge-API haben ergeben, dass das Feld schon immer Teil des Antrags war.

---

> Ich nutze für das Retrieval der Daten folgende API-URL: [https://baufismart.api.europace.de/v2/vorgaenge/{ID}/antraege](https://baufismart.api.europace.de/v2/vorgaenge/%7BID%7D/antraege)

Diese API-URL deutet darauf, dass du nicht die Anträge-API hier sondern die [Vorgänge-API](https://github.com/europace/baufismart-vorgaenge-api) nutzt. Dort ist es möglich für Vorgänge die Anträge abzurufen. Aber auch dort gab es in letzter Zeit keine Anpassungen an der API und laut [Swagger-YAML](https://[raw.githubusercontent.com/europace/baufismart-vorgaenge-api/master/swagger.yaml](https://raw.githubusercontent.com/europace/baufismart-vorgaenge-api/master/swagger.yaml)) ist das Feld `zeitpunktDerAnnahme` auch hier Teil des Antrags.

---

Kannst du uns eine Beispiel-Antwort zeigen, bei der das Feld `zeitpunktDerAnnahme` am Angebot steht? Wir möchten gerne nachvollziehen, ob und wann diese Antwort geliefert werden konnte.

**Comment by ic-hv** [comment]
@unstko Du hast recht, ich verwende tatsächlich die Vorgänge-API. 

Und - Asche auf mein Haupt - das Feld **zeitpunktDerAnnahme** stand tatsächlich nie beim Angebot. Ich musste gerade feststellen, das meine Implementierung es aber trotzdem dort ausgelesen hat, daraufhin einen Null-Value erhielt, der von der nachgeschalten Datetime-Klasse als heutiges Datum interpretiert wurde. Das hat mit PHP 7.x auch noch "super" funktioniert. PHP 8.x fing dann allerdings zu meckern an, und generierte eine Exception und ich habe mich gewundert, wieso denn "neuerdings" in $angebot['zeitpunktDerAnnahme']  null zu finden ist.
Demnach sorry für den Aufruhr hier - it was somewhat PEBKAC :)
