### ISSUE TITLE
Schreibfehler in PROVISON_AN_KUNDENBETREUER_VOLLSTAENDIG_AUSGEZAHLT

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-antraege-api#184]
Es fehlt ein I in Provision ...

**Comment by AndreKeil** [comment]
Hallo ic-hv,

vielen Dank für den Hinweis! Du hast selbstverständlich Recht: Provision schreibt sich mit zwei "i".

Eine Anpassung des ENUMs werden wir jedoch nicht vornehmen können; die damit verbundenen Implikationen - insbesondere für die bereits angebundenen Nutzer unserer API - wären einfach zu hoch.

Zum Glück sind die Systeme, welche unsere API nutzen sind, orthografisch nicht so firm wie du. ;-) ENUMs sind hier "nur" symbolische Namen für eine Reihe von Werten. API und Dokumentation passen zu einander.

Es grüßt Dich


André Keil
