### ISSUE TITLE
Der neue Tilgungsbeginn am Annuitätendarlehen im Finanzierungswunsch ist nicht stabil

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#19]
Hallo Herr Wrede,

Der neue Tilgungsbeginn am Annuitätendarlehen im Finanzierungswunsch ist nicht stabil.
Mitunter wird er auch bei KfW Darlehen und Kombidarlehen verlangt - erst nach nochmaligen
Löschen und wieder auswählen des Darlehens oder erneuten Aktualisieren kommt der Hinweis 
nicht mehr. 
Wird der Tilgungsbeginn am Annuitätendarlehen eingegeben und wieder gelöscht, 
kommt nach Aktualisieren kein erneuter Hinweis und der Antrag kann ohne Tilgungsbeginn
angenommen werden.

Im Block in der Response-Datei wird immer noch der automatische Tilgungsbeginn und nicht der manuell eingegebene Tilgungsbeginn mitgegeben - ist das so gewollt?

Eingabe: 01.12.2018 (Testantrag: KD9685/3)
  tilgung: class Tilgung {
                    anfaenglicheTilgung: 2.00
                    sonderTilgungJaehrlich: 5.00
                    tilgungsBeginnAm: 2018-12-31
                    tilgungsErsatz: null

Wie schon im vorigen Issue erwähnt - eine zeitnahe Antwort ist wichtig.
Vielen Dank!
VG, Manuela Kränz

**Comment by u00kram** [comment]
Es kann bis Montag warten. Danke.

**Comment by caspii** [comment]
@u00kram ich kann Sie nicht erreichen. Ich bin bis 16:30 am Platz.

**Comment by caspii** [comment]
Es gab bei Kombinationsdarlehen einen Fehler, dass dort auch der Tilgungsbeginn erfasst werden muss. Diesen Fehler haben wir behoben. Grundsätzlich will die Sparda BW im Eigenvertrieb immer den Tilgungsbeginn vom Berater gesetzt haben. Das ist bei den Darlehen möglich, wo Baufi Smart das Feld Tilgungsbeginn zur Verfügung stellt

**Comment by u00kram** [comment]
Hallo Herr Wrede, bei mir spielt der Tilgungsbeginn immer noch verrückt - wenn ich Änderungen in den Darlehensbeträgen und an der Aufteilung der Darlehen vornehme - erkennt BS dies nicht und möchte immer wieder den Tilgungsbeginn für ein Annu-Darlehen welche so gar nicht mehr gibt. Da hilft kein Aktualisieren und auch kein Antrag schließen und neu öffnen. Es gelingt mir nicht den Antrag anzunehmen. Wenn Sie in meinen Testantrag schauen können - dann bitte tun sie das.
EA2390 / KaufNeubau_Test4 / Pertes-KaufNeubau_Test4
Und das ist nicht der erste Test-Antrag den ich dann nicht abgeschickt bekomme ... 
Bei diesem ist auch wieder ein Kombidarlehen dabei - ok - aber der Tilgungsbeginn wird für das Annu-Darlehen mit altem Betrag (158.000 euro / neu 58.000 Euro) gefordert.
Nehme ich das Kombidarlehen wieder raus - wird weiterhin hartnäckig der Tilgungsbeginn für das Annu-Darlehen gefordert - nun für den angepassten Betrag, aber es ist gesetzt.
Fazit: Sobald nochmal Änderungen bei den Darlehen vorgenommen werden, bekomme ich den Antrag erstmal nicht angenommen.
Bitte unbedingt nochmal anschauen - vielen Dank.

"Grundsätzlich will die Sparda BW im Eigenvertrieb immer den Tilgungsbeginn vom Berater gesetzt haben. " - soweit so gut. 
Dann wird der manuell gesetzte Tilgungsbeginn jetzt auch in der Response-Datei mit übertragen?
Danke und VG, Manuela Kränz

**Comment by u00kram** [comment]
Gerade habe ich nach der Änderung des Betrages vom Annu-Darlehen den Tilgungsbeginn nochmal rausgelöscht und dann nochmal neu eingegeben ... das hat BS dann angenommen ... AP5627

**Comment by caspii** [comment]
Hallo Frau Kränz, 
Bin mir gerade nicht sicher anhand ihrer Aussagen ob sie den Fehler noch sehen oder nicht

**Comment by u00kram** [comment]
Ja ich sehe ihn noch. Allerdings auch entkoppelt vom Kombidarlehen.

**Comment by caspii** [comment]
Hallo Frau Kränz,

das was sie gesehen haben waren Nachwehen von einer Änderung in unserem System. Sie haben sich vermutlich die Angebote vor dieser Änderung gemerkt. Es müsste jetzt alles funktionieren. Falls sie noch testen wollen, dann bitte mit neu gemerkten Angeboten.

**Comment by u00kram** [comment]
Hallo Herr Wrede, 
danke. Eine Besserung ist schon eingetreten, meine letzten Anträge waren absendbar. Nächste Tests gibt es erst ab dem 3.12. wieder. Wenn mir noch etwas auffällt, melde ich mich. Danke und VG, Manuela Kränz
