### ISSUE TITLE
Leere Liste ausgeben, falls keine Anträge vorhanden

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#26]
Wenn keine Anträge in einem Vorgang sind, liefert die Antraege API:
Response: 200
```{
    "_links": {
        "self": {
            "href": "https://baufismart.api.europace.de/v2/antraege/ZE9389"
        }
    }
}
```

SOLL: API sollte eine leere Liste liefern, um deutlich zu machen, dass keine Anträge vorhanden sind

### Input von Michael Grabow:
as mit dem 200er finde ich OK. Aber meine Erwartung wäre es, dort dann eine leere Liste mit den Anträgen zu bekommen. Aktuell muß bei Verwendung der API auf NULL geprüft werden und das versucht man eigentlich durch die Verwendung von 'Optional' in Java zu vermeiden.
Wenn ich die Spezifikation richtig verstanden habe, dann sind in der API aber sowieso alle Rückgabewerte optional...

**Comment by FabianStuehler** [comment]
Das machen wir mit der API v3.
