### ISSUE TITLE
Keine Kubatur aus den Zusatzangaben übertragen/mitgegeben 

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#27]
Hallo zusammen,
die Kubatur für ein HAUS (egal welche Art und Typ) aus den Zusatzangaben wird nicht in der Response/API übertragen/mitgegeben - nur die Wohnfläche aus den Basisangaben.
Dies wurde von der Bank in den Releasetests angemerkt.
Was ist dazu in Planung?
Danke und VG, Manuela Kränz

**Comment by u00kram** [comment]
Wie schaut es denn mit dem Thema aus? Danke.

**Comment by K0ne** [comment]
Die kubatur wird mitausgegeben: siehe screenshot.

oder meinen Sie eine andere Stelle?

<img width="628" alt="bildschirmfoto 2019-01-30 um 13 22 36" src="https://user-images.githubusercontent.com/11558781/51981061-266ccb00-2492-11e9-8e29-aa6d60487aac.png">
![bildschirmfoto 2019-01-30 um 13 22 07](https://user-images.githubusercontent.com/11558781/51981062-266ccb00-2492-11e9-960c-669836e616e0.png)

**Comment by caspii** [comment]
@K0ne fehlt in dem Kommentar noch ein Screenshot?

**Comment by u00kram** [comment]
Hallo zusammen,

hier war ich noch eine Antwort schuldig - sorry.
Damals wurde die Kubatur in der Anträge API nicht mitgegeben und somit konnten wir sie nicht mappen. Ist dies inzwischen geändert?
Danke und VG, 
M.Kränz

**Comment by u00kram** [comment]
Testfall vom 26.2.19 Y04096/3 - keine Kubatur in der API-Anträge mitgegeben.

**Comment by caspii** [comment]
Die Kubatur wird ausgegegeben!

Aufruf: GET https://baufismart.api.europace.de/v2/antraege/Y04096/3

Response
```
                  "gebaeude": {
                        "anzahlDerWohneinheitenImGebaeude": 3,
                        "anzahlVollgeschosse": 4,
                        "ausstattung": "MITTEL",
                        "baujahr": 2010,
                        "bauweise": "MASSIV",
                        "dachgeschossAusbau": "VOLL_AUSGEBAUT",
                        "hausAnordnung": "FREISTEHEND",
                        "hausTyp": "MEHRFAMILIENHAUS",
                        "kubatur": 2000,
                        "unterkellerung": "UNTERKELLERT",
                        "wohnflaeche": {
                            "gesamtGroesse": 434.53,
                            "vermietungsInformationen": {
                                "nutzungsArt": "TEIL_VERMIETET"
                            }
                        },
                        "zustand": "MITTEL"
                    },

```

Bitte Ticket erneut öffnen, falls es anders ist

**Comment by u00kram** [comment]
Vielen Dank für die Info.
Ich bekomme in meiner Response-Datei noch keine Kubatur mitgegeben, weil wir noch nicht die aktuelle Version der Anträge API verwenden, dahingehend wurde ich heute von der Entwicklung informiert.  
Nun weiß ich zukünftig in welche Richtung ich recherchieren muss.
Die neue Version ziehen wir nach dem Urlaub des Entwicklers - Mitte Mrz. 
Danke und VG, Manuela Kränz
