### ISSUE TITLE
Berechtigung zur Abholung von Genopace-Anträgen für Nbg.

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#28]
Hallo Herr Wrede,
wir haben heute über den User von Andreas Tauber (CEP53), dem auch die Plakette von Nbg. für den Zugriff zugeordnet ist, versucht einen Antrag: HW2121/1  von Nbg. einzeln abzuholen.
Meldung:
Http 403 - also Status Forbidden 
Die SpB Nbg. hat den Nutzung des EPAs angefragt und wir wollten den Zugriff auch auf Genopace-Anträge testen. Der Endpunkt sollte der gleiche sein?!
Technische User etc. beauftragen wir, wenn Nbg. das Go gibt.
Bisher sollte es nur ein Test als Durchstich sein.
Bitte berechtigen Sie uns auch für Anträge von den Usern der SpB Nbg.
Danke.
Ich bin erst am Montag 17.12. wieder im Büro.
VG, Manuela Kränz

**Comment by caspii** [comment]
Hallo Frau Kränz,

der User CEP53 hat bisher nur Zugriff auf Testgeschäft. Der Antrag HW2121/1 ist Echtgeschäft. Wollen sie, dass wir den Nutzer für Echtgeschäft freischalten?

**Comment by u00kram** [comment]
Hallo Herr Wrede,
aja, da habe ich ein Echtgeschäft erwischt, nein das soll nicht sein. Und nein den User CEP53 nicht für Echtgeschäft freischalten - danke.
Wie sehe ich denn, welcher Antrag von der SpB Nbg. ein Testantrag ist. Ich schaue mit meinem Admin User: Manuela Kränz auf die Antragsübersicht.
Gern können Sie mir auch zwei drei Testanträge nennen, möglichst nicht zu alt - dann wiederholen wir den Test.
Danke und VG, Manuela Kränz

**Comment by caspii** [comment]
Sie können auf der Startseite auf die Testumgebung schalten. Mehr dazu hier: https://europace2.zendesk.com/hc/de/articles/360008895313-Testumgebung-sinnvoll-nutzen

Sobald sie in der Testumgebung sind, können sie auf die Antragsübersicht wechseln. Hier wird ihnen im UI deutlich gemacht, dass sie weiterhin in der Testumgebung sind. Alle Anträge die sie hier sehen sind Testanträge.

**Comment by u00kram** [comment]
a) Danke. Es war mir nicht bewusst, dass ich bei der Anmeldung mit dem AdminUser direkt im Echtgeschäft lande. Bei meinem zweiten User: Manuela1 Kraenz1 bin ich automatisch in der Testumgebung - ich erstelle aber auch nur Anträge mit diesem User.
Allerdings gibt es beim AdminUser  in der Übersicht 6 Neue Vorgänge (Echtgeschäft) ohne Inhalt/Daten - kann ich diese irgendwie löschen - sie werden nie in Bearbeitung genommen. Die Archivierung erfordert einen Grund, damit gehen die Anträge in die Statistik ein? 
b) Wir haben einen Testantrag (EN9111/1) von der SpB Nbg. über die EPA-Schnittstelle abholen können. Sprich, es können Europace und Genopace-Anträge abgeholt werden. Gut.
In der Response-Datei gibt es keinen Hinweis auf Europace oder Genopace? Bzw. Europace wird in allen Links genannt ... weil es nur eine API gibt, richtig? 
Dies nur zur Info für uns. 
Danke!

**Comment by caspii** [comment]
a) Sie können die Vorgänge archivieren, ohne Gründe anzugeben. Anträge werden dabei keine erzeugt. Ein Antrag wird erst erzeugt, sobald ein Angebot in einem Vorgang angenommen wird
b) technisch gibt es keine Unterscheidung zwischen Europace und Genopace. Es gibt nur eine API.
