### ISSUE TITLE
Anträge fehlen in der antraege-api

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#30]
Hallo Herr Wrede,
folgende Anträge wurden von der Bank als NICHT in globo angekommen gemeldet, der EPA hat sie aber auch nicht anfragen können. Keine Bereitstellung in der Anträge API.
YK4210/1 (9.1.) und LG2328/3 (10.1.)
Zum Antrag LG2328/ gab es vorher schone einen LG2328/2 - der wurde übertragen. 
Bitte lassen Sie prüfen, was eine Bereitstellung und damit Abholung blockiert.
Danke und VG, Manuela Kränz

**Comment by u00kram** [comment]
Nachtrag: Die beiden Anträge sollten nachträglich nicht mehr zur Übertragung bereitgestellt werden. Sie wurden schon manuell in globo eingegeben.

**Comment by caspii** [comment]
Hallo Frau Kränz,

entschuldigen sie die verspätete Antwort. Können sie mir bitte die Partner ID der Plakette nennen, mit dem der Aufruf nicht geklappt hat? Mit meinem Nutzer konnte ich jedenfalls beide Anträge über die antraege-API aufrufen.

**Comment by u00kram** [comment]
Hallo Herr Wrede,
für die Produktion nutzten wir immer den TechnUser u60epap / PartnerID:  GPI08
Eventuell gab es nur ein temporäres Problem, dass die Anträge nicht zur Abholung gelistet wurden.
Irgendwie müssen wir aber solche Probleme analysieren, um besser reagieren zu können.
Wir haben auf unserer Seite nach den Anträgen und/oder Meldungen dazu gesucht, nichts zu finden. 
Vielleicht finden Sie noch einen Fehlerhinweis.
Danke und VG

**Comment by u00kram** [comment]
Hallo Herr Wrede,
Hier wieder so ein Fall - im EPA Produktion ist der Antrag  SZ3754 nicht bekannt und wir 
haben auch keine Fehlermeldung bekommen.
Bitte lassen Sie schnellstmöglich prüfen, was mit dem Antrag ist.
Verwendete PartnerID ist nach wie vor in Produktion: PartnerID: GPI08
Ihnen vielen Dank.
Mit freundlichen Grüßen
Manuela Kränz

**Comment by caspii** [comment]
Hallo Frau Kränz,
ich habe gerade den Antrag für SZ3754 mit der Plakette GPI08 abholen können.
Können sie es erneut versuchen?
Damit wir in die Fehleranalyse gehen können, wäre ein geanuer Timestamp für uns wichtig

@K0ne @ollio Es wäre Sinnvoll, dass wir in solchen Fällen immer eine TraceID ausgeben

**Comment by u00kram** [comment]
Der EPA läuft alle 10 min und eine TraceID gibt es bei den nicht aufgelisteten Anträgen ja im EPA nicht. Es gibt den Antrag nicht und auch keine Meldung oder einen Eintrag in der EPA-DB dazu.
Wir sind auch etwas ratlos. Das Problem gibt es erst neuerdings - also seit dem 9.1. - vorher gab es keine Anträge ohne Auflistung. 
Derzeit könnte der Vermittler von BW den Antrag nur stornieren und nochmal neu abschicken und wir müssen schauen, ob er dann abgeholt wird?
Grundsätzlich können wir in der EPA-DB eine Zeile für einen Antrag mit Wiederhole eintragen - aber für die Produktion ist dieser Prozess noch nicht vorgesehen und würde derzeit zu lange dauern.

**Comment by caspii** [comment]
Beobachtung:
Über `https://baufismart.api.europace.de/v2/antraege/SZ3754` ist der Antrag abrufbar, aber bei Abruf von `https://baufismart.api.europace.de/v2/antraege/` fehlt er. Wieso?

**Comment by K0ne** [comment]
Der Antrag wird mit einem standard limit von 10 nicht gefunden. Mit  /v2/antraege/?limit=20 schon.
Oder einfach mit dem next link: "https://baufismart.api.europace.de/v2/antraege/?datenKontext=ECHT_GESCHAEFT&sort=absteigend&page=1&limit=10.

Die Sortierung ist default: zeitpunktDerAnnahme Absteigend.

**Comment by caspii** [comment]
Hallo Frau Kränz,

Um den obigen Kommentar noch mal zu verdeutlichen: Die API verhält sich korrekt. Es werden immer nur 10 Anträge zurückgeliefert, wie hier dokumentiert ist: https://htmlpreview.github.io/?https://raw.githubusercontent.com/hypoport/antraege-auslesen-api/master/Dokumentation/index.html#_getalleantraege

Um weitere Anträge abzurufen, kann können die 2 Wege wie im obigen Kommentar beschrieben verwendet werden.

**Comment by u00kram** [comment]
Hallo Herr Wrede, (per Mail am 25.01.2019 verschickt)

bitte schließen Sie meine Tickets nicht, wenn ich keine letzte positive Rückmeldung eingegeben habe.
Meine Tickets möchte ich schließen - danke.

Dieses Ticket ist noch nicht erledigt.
Wir haben noch keine Lösung oder wirkliche Erklärung für das Problem, dass Anträge in der Anträge API
vom EPA nicht gelesen werden können, weil sie in der Antragsliste zur Abholung nicht enthalten sind. 

Wir holen mit folgender URL alle 10 min mit derzeitigem Limit von 1000 Antägen ab.
https://baufismart.api.europace.de/v2/antraege?datenKontext=TEST_MODUS&angenommenNach=2019-01-22T15:10:49.868%2B01:00&limit=
Bis Mitte Jan 2019 hat dies auch wunderbar funktioniert. Es stehen pro Abholung derzeit eher weniger als 10 Anträge bereit. 
Da die abgeholten Anträge in der Anträge API nicht als abgeholt gekennzeichnet werden, arbeiten wir mit dem Kriterium: angenommenNach 
- Neue Abholung aller Anträge nach dem Letzten Zeitstempel der Abholung.

Ein Abholversuch speziell einer Antragsnummer ist nicht mit dem Abholverfahren des EPA zu vergleichen.

Wir sprechen auch hier (wie schon am 9./10.01.) von Anträgen aus der Produktion, die wir nicht übertragen können.
Herr Konitzer möchte bitte Herrn Tauber (+49 911 9291-2532) bis 13:30 Uhr noch anrufebn und die beiden Techniker möchten bitte das 
Problem noch einmal direkt besprechen - nur so kommen wir zu einer schnellen Lösung.

Wie haben das Thema schon mal besprochen - wenn wir bei einem akuten technischen Problem nicht weiterkommen,
dann muss es möglich sein, dass unsere Entwickler auch mal persönlich sprechen.

Ihnen und Herrn Konitzer vielen Dank.

**Comment by caspii** [comment]
Hallo Frau Kränz,

seitdem sind ja Herr Tauber und Herr Konitzer intensiv in Kontakt gewesen und es wird an der Problematik gearbeitet.

Zum Thema Ticket schliessen: bitte haben sie Verständnis dafür, dass wir Tickets schließen, wenn wir der Meinung sind, dass sie behoben sind. In diesem Fall lagen wir falsch, aber dafür können sie ja das selbe Ticket wieder öffnen. Wir können uns nicht darauf verlassen, dass alle Tickets von den Erstellern geschlossen werden und wir möchten auch keine Ausnahmen in dem Prozess definieren.

**Comment by K0ne** [comment]
Mail an SDV: 

Hallo Andreas,
 
das Problem liegt meiner Meinung nach an der Zeit zwischen der Annahme und dem indizieren (wann der Antrag gefunden werden kann).
Hier kann es bei vollen Queues zu Verzögerungen kommen, sodass ihr bei euren Abfragen etwas in die Vergangenheit gehen müsst, um auch alle Anträge zu erhalten.
 
Z.B. bei der Abfrage um 17:00 mit angenommenNach=16:55 geht ihr auf angenommenNach=16:53. Dadurch werdet ihr des Öfteren doppelte Anträge erhalten, aber auch wirklich alle!
 
Wäre das möglich?
 
Bei dem Fehlerfall am 9.1. sind mir eure Anfragezeiten nicht ganz klar, aber der Fall spiegelt das Problem ganz gut wieder.
 
Nicht gefundener Antrag: „YK4210“ (angenommenNach am 2019-01-09 um 17:03:23.986)
 
Anfrage 1:
17:02:37,061   mit angenommenNach 16:55:01.9    <- Hier kann er noch nicht enthalten sein
17:03:37,223   mit angenommenNach 17:02:36.609    -> Hier könnte es bei einer Verzögerung von 15 Sekunden passieren, dass er nicht enthalten ist.
17:03:40,279   mit angenommenNach 17:03:36.673   <- Hier kann er noch nicht enthalten sein
17:05:02,420   mit angenommenNach=17:03:39.772
17:12:37,055   mit angenommenNach 17:05:01.983
 
Auch bei 4 verschiedenen Clients, die ihr verwendet, sehe ich Aufrufe, die nicht jede 5 oder 10 Minuten request machen?!
 
Wäre es möglich Client spezifische Trace IDs zu verwenden, damit wir in Zukunft schneller Fehler finden können.
 
Grüße
 
Martin

**Comment by u00kram** [comment]
Einige Mails weiter / 4.2.19 / Mail Martin Konitzer an Andreas Tauber
Hallo Andreas,
 
leider war ich den Freitag nicht erreichbar. Nichtsdestotrotz habe ich hier nochmal die Problematik diskutiert.
Es wird in naher Zukunft keinen zustandbasierten Endpunkt geben, durch den Ihr nur die noch nicht ausgelieferten Anträge erhalten könnt.
 
Anträge können wie bisher mit dem genutzten Endpunkt “/antraege“ abgerufen werden. Die zeitliche Lücke zwischen dem Anlegen und dem Gefunden beträgt im standardfall 2 bis 3 Sekunden. Um auch größere Lücken von ca. 30 Sekunden zu bewältigen muss sich das Suchintervall überlappen. 
 
Beispiel: 
Anfrage 1 um 17:00:00 mit “angenommenNach=16:50:00“
Anfrage 2 um 17:10:00 mit “angenommenNach=16:59:00“
 
Dadurch muss mit doppelten Anträgen umgegangen werden.
Ich hoffe wir können heute Nachmittag telefonieren. Ich versuche dich anzurufen.
Grüße
Martin

**Comment by u00kram** [comment]
Mail Antwort
Guten Morgen Martin,
ich verstehe natürlich, dass man den Endpunkt maximal zustandlos halten will ...
Ich hatte gedacht, dass es so etwas wie einen Antragstatus bereits gibt und es evtl. leicht wäre eine Abfrage zu definieren, welche als Resultat die "nicht gelieferten" Anträge ausgibt.

Letztlich verlagern wir den Zustand in das EPA Projekt, der Lücken oder Duplikate vermeiden soll. Wir heilen die Problematik am Client, bauen einen Workaround durch überlappende Zeiträume bei der Abfrage.
Wie bereits besprochen, empfand ich Nutzung und Fortschreibung eines Zeitstempels bei Umsetzung von EPA als nicht besonders Vertrauens erweckend.
Meiner Ansicht wäre es die Beste Lösung, wenn die API die Abfrage nicht gelieferter Anträge ermöglicht.

Letztlich können wir den Umgang mit doppelten Anträgen in EPA umsetzen und haben das bereits eingeplant.
Ich würde das gerne telefonisch mit dir besprechen.

Wir haben auch eine User Story zu besserer ClientID eröffnet, was ich mit dir besprechen möchte.
Bis heute Nachmittag
Grüße
Andreas

**Comment by u00kram** [comment]
Von:	"Konitzer, Martin" <Martin.Konitzer@europace.de>
An:	"andreas.tauber@sdv-it.de" <andreas.tauber@sdv-it.de>
Kopie:	"von Wrede, Caspar" <caspar.wrede@europace.de>, "manuela.kraenz@sdv-it.de" <manuela.kraenz@sdv-it.de>
Datum:	11.02.2019 16:25
Betreff:	Re: WG: Re: WG: Anträge API Problematik - Nicht alle Anträge werden gefunden 
Hallo Andreas,
ich habe die Frage gerade ins Team gebracht und gebe dir so schnell wie möglich eine konkrete Antwort.
Liebe Grüße
Martin

**Comment by u00kram** [comment]
Mail vom 4.3.19
Hallo Martin,
seit ihr hier zu einem Ergebnis gekommen? 
Wie angemerkt möchte ich die Spanne für überlappende Anfrage Zeiträume möglichst gering halten ... komm ich mit 3 oder 4 Sekunden aus?

Bitte gib mir bis Mittwoch eine Rückmeldung, so dass ich vor meinem Urlaub :> einen Wert an die Kollegin weitergeben kann.

Danke

Grüße aus Nürnberg, Andreas

Java Entwickler
Digital Solutions – Enterprise Architecture and APIs
_________________________________________

**Comment by u00kram** [comment]
Mail vom 6.3.2019
Hallo Andreas,
 
ich bin hier nochmal in die Runde gegangen und aktuell müsst ihr noch mit einer möglichen Lücke von 2 Minuten rechnen. 
Wir arbeiten daran, dass wir hier die Lücke schließen werden. Heißt ihr müsst damit rechnen, dass ihr bei der Überschneidung doppelte Anträge erhaltet.
Grüße
Martin

**Comment by u00kram** [comment]
Hallo zusammen,
eine Lücke von 2 Minuten ist schon nicht ganz ohne. Unsere Umsetzung ist eigentlich keine Lösung des Problems, sondern nur ein Workaround.
Das ist aber wohl beiden Seiten bewusst:  Bitte unbedingt die Lücke zeitnah schließen. 
Vielen Dank.
Manuela Kränz

**Comment by FabianStuehler** [comment]
Das ursprüngliche Problem wurde an der Antrags API gefixt und es werden nun alle Anträge ausgegeben.

**Comment by Integer93** [comment]
@u00kram Wir haben vor kurzem ein Caching-Problem an der API gelöst. Besteht das Problem nach wie vor? Es kann nach wie vor zu einer Verzögerung von wenigen Sekunden kommen zwischen Antragsstellung und Ausgabe an der API.

**Comment by FabianStuehler** [comment]
Ich schließe hiermit dieses issue.
