### ISSUE TITLE
Angabe Grundstück - bereits bezahlt - fehlt in der API

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#31]
Bei der Eingabe der Kosten unter Vorhaben, kann beim Grundstück erfasst werden, ob es bereits bezahlt ist.  Diese Information wird über AnträgeAuslesen aber nicht mit ausgeliefert. Das führt dazu, dass bei den Partnern die Fälle mit Finanzierungslücke ankommen, da der Preis des Grundstücks in der aktuellen Finanzierung gar nicht berücksichtigt ist.

Wir benötigen bitte die Angabe "bereits bezahlt" in der API.

![image](https://user-images.githubusercontent.com/37293326/51377496-579ce100-1b0b-11e9-8fd2-94cf1c76817b.png)

**Comment by caspii** [comment]
Über vorgaenge-API kommt der Wert
```
        "finanzbedarf": {
            "bereitsBeglichen": 8888,
            "grunderwerbsteuer": 0,
            "grundstuecksKaufpreis": 8888,
            "grundstueckBereitsBezahlt": true,
            "notargebuehr": 0
        },
````

Über antrage-API nicht:
```

                    "finanzbedarf": {
                        "bereitsBeglichen": 8888,
                        "grunderwerbsteuer": 0,
                        "grundstuecksKaufpreis": 8888,
                        "notargebuehr": 0
                    },


```

**Comment by hripp** [comment]
Erledigt mit Release 2.9.
