### ISSUE TITLE
Fehlendes Unterscheidungsmerkmal bei "bestehenden Darlehen am Finanzierungsobjekt" 

### ISSUE THREAD

**Issue by hripp** [europace/baufismart-antraege-api#32]
In der Liste der "bestehenden Darlehen am Finanzierungsobjekt" sind alle bereits bestehenden, der Immobilie gegeordnete, Darlehen aufgeführt. Zusätzlich aber auch Bausteine/Darlehen der aktuellen Finanzierung, die nicht dem jeweiligen Teilantrag/Kreditentscheider zugeordnet und damit nicht unter angebot.darlehen zu finden sind.
Es fehlt nun die Möglichkeit Letztere von Ersten zu unterscheiden.

**Comment by caspii** [comment]
Neues Feld soll heißen istBausteinDerAktuellenFinanzierung

**Comment by ollio** [comment]
EP2 Core: AngebotFuerKeTvErsteller Zeile 222

**Comment by hripp** [comment]
Wird mit #33 gefixt.

**Comment by ollio** [comment]
https://github.com/europace/baufismart-antraege-api/issues/33
