### ISSUE TITLE
Sicheres Zuordnungsmerkmal zwischen "Darlehen am Angebot" und "Bestehendes Darlehen am Finanzierungsobjekt""

### ISSUE THREAD

**Issue by hripp** [europace/baufismart-antraege-api#33]
In der Liste der "bestehenden Darlehen am Finanzierungsobjekt" können sich auch Bausteine/Darlehen der aktuellen Finanzierung, die nicht dem jeweiligen Teilantrag/Kreditentscheider zugeordnet und damit nicht unter "Darlehen am Angebot" zu finden sind, befinden.
Bekommt man nun für eine Antragsnummer zwei Teilanträge (Sichtbarkeit/Berechtigung für beide Kreditentscheider), so findet sich das "Darlehen am Angebot" des einen Teilantrags immer auch als "bestehendes Darlehen am Finanzierungsobjekt" des anderen Teilantrags.

Um nun eine Übersicht über alle Bausteine der aktuellen Finanzierung zu erhalten und davon ausgehend das bei kombinierten Angeboten nicht immer Sichtbarkeiten/Berechtigungen für weitere Teilanträge vorhanden sind, entnehmen wir die Informationen vorrangig aus der Liste der "bestehenden Darlehen am Finanzierungsobjekt" (in diesem Zusammenhang, siehe auch: 
https://github.com/europace/baufismart-antraege-api/issues/32).

Ist jedoch ein weiterer Teilantrag mit detaillierteren Informationen zu den Bausteinen vorhanden, so sollen Diese verwendet und das entsprechende "bestehende Darlehen am Finanzierungsobjekt" ignoriert werden.
Hier fehlt nun das sichere Zuordnungsmerkmal. Die am "bestehenden Darlehen am Finanzierungsobjekt" vorhandene "id" entspricht leider nicht der "bausteinId" des zugehörigen "Darlehens am Angebot".

**Comment by caspii** [comment]
Entscheidung, ID sollte Baustein ID entsprechen (siehe letzter Satz)
