### ISSUE TITLE
Fehlendes Unterscheidungsmerkmal bei "bestehenden Darlehen am Finanzierungsobjekt"

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#35]
In #32 wird das Problem beschrieben. Es handelt sich um ein Broken Window was als Quickfix via #32 behoben wurde.

Für den nächsten Release sollten die Bausteine der aktuellen Finanzierung in einem eigenen Knoten untergebracht werden.

cc @ollio

**Comment by ollio** [comment]
Was ist der Unterschied zu https://github.com/europace/baufismart-antraege-api/issues/33 ?

**Comment by ollio** [comment]
https://github.com/europace/baufismart-antraege-api/issues/33

**Comment by caspii** [comment]
@ollio Ich hatte #33 als Quickfix verstanden und diesen Task als die "richtige" und nachhaltige Lösung
