### ISSUE TITLE
Eintrag in Ereignisse ohne Statuswechsel

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#36]
Leider ist es derzeit nicht möglich, einen Eintrag in den Ereignissen vorzunehmen, ohne auch gleichzeitig den Status des Falls zu verändern.

Wir haben mehrere Anwendungsfälle, in denen wir gerne ein Ereignis an den Fall schreiben würden, der Status des Falls aber unverändert bleibt. Z.B.:
- erfolgreicher Fallexport an die Fiducia: wir würden dem Anwender gerne Info geben und gleichzeitig die Fall-ID der Fiducia mitliefern
- nicht erfolgreicher Fallexport: wir würden dem Anwender auch gerne diese Info mitteilen
- Dokumente, die nicht versendet werden konnten, da sie zu groß sind: auch diese Info würden wir dem Anwender gerne mitteilen

**Comment by caspii** [comment]
> erfolgreicher Fallexport an die Fiducia: wir würden dem Anwender gerne Info geben und gleichzeitig die Fall-ID der Fiducia mitliefern

Fall-ID kann vom PA gesetzt werden

> nicht erfolgreicher Fallexport: wir würden dem Anwender auch gerne diese Info mitteilen

Statuswechsel auf `zurückgestellt` mit Ereignismeldung

> Dokumente, die nicht versendet werden konnten, da sie zu groß sind: auch diese Info würden wir dem Anwender gerne mitteilen

Idee: wir verschicken eine Mail an den PA mit Links auf die Dokumente.
