### ISSUE TITLE
Partnerkennzeichen des Vermittlers mit ausliefern

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#37]
Aufgekommen ist bei uns diese Anforderung durch die DZ HYP, die sich gerade an die Anträge-API anbindet. Vermittler haben bei der DZ HYP eine Vermittlernummer, die sie bei uns im Partnerkennzeichen hinterlegen. Ohne dieses Kennzeichen ist eine Annahme des Falls nicht möglich. Im Backend der DZ HYP erkennt die DZ HYP den Geschäftspartner anhand dieser Nummer wieder.

Die DZ HYP benötigt darum die Vermittlernummer auch über die Anträge-API, da sonst ein Zuordnen des Falls nicht möglich ist.

Wichtig: Werden Partnerkennzeichen ausgeliefert, darf nur das Kennzeichen des abfragenden Partners geliefert werden. Nicht die Kennzeichen anderer Partner.

**Comment by caspii** [comment]
Klären, was das fachlich bedeutet

**Comment by caspii** [comment]
Fachlich habt ihr hier das "go"! ✅

**Comment by hripp** [comment]
Erledigt.
