### ISSUE TITLE
Vertriebsorga-ID in die Daten der Vertriebsorganisation mit aufnehmen

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#38]
Hintergrund der Anforderung ist der Wunsch der Produktanbieter, ermitteln zu können, woher das Geschäft kommt, z.B. Europace, Genopace, Baufinex, Starpool, ...

Aktuell weisen wir nur den Klartextnamen der Vertriebsorganisation aus. Dieser ist jedoch sehr vage, da sich durch Fusionen, z.B. im Geno-Bereich, viel ändern kann. Sicheres Kennzeichen zur Indentifikation der Vertriebsorganisation wäre die Vertriebsorga-ID.

Die Vertriebsorga-ID geben wir auch im Produzentenreport mit aus, z.B. Smart Facts Produktanbieter.

**Comment by lisascholz** [comment]
![image](https://user-images.githubusercontent.com/37293326/53722116-17988000-3e65-11e9-9adc-c51a95b5ccb9.png)

**Comment by caspii** [comment]
Klären, ob das fachlich OK ist.

**Comment by caspii** [comment]
Let's do it
