### ISSUE TITLE
Vermögenswerte bei mehreren Haushalten

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#39]
Wenn Vermögenswerte aus mehreren Haushalten in die Finanzierung eingebracht werden, werden die einzelnen Vermögenswerte an die SST mit korrektem Nominalbetrag übergeben, der "maximal aufzulösende Wert" wird jedoch jeweils aufsummiert und bei jedem Haushalt angegeben. (Laut Aussage der DZ HYP passiert das grundsätzlich bei allen Vermögenswerten.)

Testfall Q90054/1, erfasst sind zwei Haushalte, jeweils Bank- und Sparguthaben. Der Vermögenswert wird pro Haushalt ausgewiesen, bei der aufzulösenden Position werden beiden Werte aus beiden Haushalten addiert.

SOLL:
Pro Haushalt und Vermögenswert soll nur der Betrag als aufzulösen angegeben werden, der für diesen Haushalt und Vermögenswert als aufzulösen erfasst wurde.

**Comment by jhackel-hypo** [comment]
Kann geschlossen werden. Gefixt mit https://github.com/hypoport/antraege-edge-server/pull/37

**Comment by jhackel-hypo** [comment]
Erledigt.
