### ISSUE TITLE
globo Stammnummer aus dem Feld: Eigene Vorgangsnummer in API-Anträge bereitstellen

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#40]
Guten Tag,
über die schreibende Schnittstelle von globo nach Baufi Smart wird nun auch die Stammnummer (auch Kundennummer genannt) nach BS in das Feld: Eigene Vorgangsnummer gemappt.
Diese Stammnummer muss durch den EPA ausgelesen und mit den Antragsdaten wieder nach globo in den neuen Vorgang gemappt werden.
Wo und mit welcher Bezeichnung wird diese Stammnummer in der API-Anträge mitgegeben?
Diese Umsetzung wird für die Sparda-Banken zeitnah benötigt.
Vielen Dank und viele Grüße
Manuela Kränz

**Comment by caspii** [comment]
Auf produktanbieter Seite heißt die Stammnummer `antragsReferenz`. Wie das gesetzt wird steht hier: https://github.com/europace/baufismart-antraege-api#die-antragsreferenz-eines-antrags-setzen

Ich habe es gerade gestestet. Es funtkioniert.

**Comment by u00kram** [comment]
Danke - habe ich an Andreas Tauber weitergegeben. Er schaut es sich an - bei Fragen meldet er sich - bis dahin lassen wir das Ticket noch offen. VG

**Comment by u00kram** [comment]
Testabholung nicht erfolgreich: (neue Version 2.9. ist in Entwicklung gezogen)
Test antragsNummer: PC9799/1/1
        antragsReferenz: null 
"Eigene Vorgangsnummer" in BS ist mit 581340 befüllt.
Woran kann es liegen?

**Comment by u00kram** [comment]
Hier benötigen wir dringend eine Lösung - diese Umsetzung muss ins nächste Release und dieses soll sehr zeitnah anrollen. Danke.

**Comment by caspii** [comment]
Ich habe in ihren Testantrag (PC9799/1/1) gerade eine `antragsReferenz` schreiben können. Wenn sie ihn jetzt abholen, müssten sie das sehen können.

Wie habe ich es gemacht?

Mit `PATCH https://baufismart.api.europace.de/v2/antraege/PC9799/1/1`
Body:
```
[
	{ "op": "add", "path": "/antragsReferenz", "value": "TEST1234" }
]
```

**Comment by u00kram** [comment]
Danke. Ihr Eintrag: Test1234  wurde nun auch zur Übertragung bereitgestellt - soweit so gut.
Allerdings hat der Antrag in der Baufi Smart-Oberfläche die "Eigene Vorgangsnummer:" 581340
Soweit ich intern informiert bin, ist dies das Feld, wo die Stammnummer vom Berater in Baufi Smart eingetragen wird oder wohin sie über die Schreibende Schnittstelle nach Baufi Smart geschrieben wird. Und diese muss dann bei der Antragsabholung wieder mitgegeben werden.

**Comment by caspii** [comment]
Die "Eigene Vorgangsnummer" des Produktanbieters wird auf der Ereignisse Lasche angezeigt:

![image](https://user-images.githubusercontent.com/3215971/55418534-2ad96100-5573-11e9-8189-f622e9e22be3.png)

Ich schliesse jetzt dieses Ticket, sie können es ja nochmal öffnen, falls es noch Fragen gibt

**Comment by u00kram** [comment]
Ich habe mir nochmal einen neuen Testfall geben lassen, in den die Stammnummer geschrieben wurde. H37694
Bitte mal anschauen. Die Stammnummer (581332 ) steht nicht unter den Ereignissen! sondern wie auch von Fabian Stühler informiert, in der Vorgangslasche unter Eigene Vorgangsnummer. Und genau diese Nummer müssen wir wieder mit den Antragsdaten abholen. 
Wenn diese Nummer nicht über antragsReferenz mitgegeben wird, dann ist dies nicht der Weg. 
Können Sie sich dazu bitte mit Herrn Stühler nochmal absprechen - wir brauchen hier dringend eine Klärung. Vielen Dank.

**Comment by caspii** [comment]
Der Vorgang H37694 hat kein Antrag! Wieso wollen sie zu diesem Vorgang dann ein Antrag abholen?

**Comment by u00kram** [comment]
Nein der Vorgang hat noch keinen Antrag - soweit bin ich noch nicht. Bisher geht es erstmal nur um die Stammnummer, die schon nach Baufi Smart aus unserem System geschrieben wurde und Sie sich bitte das Zielfeld anschauen sollten -  in der Vorgangslasche unter "Eigene Vorgangsnummer".
Diese geschriebene Stammnummer erscheint nicht bei den Ereignissen.
Wenn wir uns dann einig sind, wohin die Stammnummer geschrieben wird, dann müssen Sie bitte klären, wie wir sie dann über die Antragsdatenbereitstellung in der Anträge API wieder mitgegeben bekommen. 
Es sieht NICHT so aus als ob die Angabe unter antragsReferenz die richtige Nummer ist. Im Antrag:  Testantrag (PC9799/1/1) stand Test1234 - wie von Ihnen hinterlegt, aber nicht die von uns gelieferte/geschriebene Stammnummer: 581340. Diese wird bisher mit den Antragsdaten über die Anträge API nicht mitgegeben. 
Hier liegt der Knackpunkt.

**Comment by caspii** [comment]
feature ticket ist #47. Dieses Issue wird geschlossen
