### ISSUE TITLE
 CreditLife und BaufiProtect Umsetzung in Baufi Smart - Termin / Daten / - bereitstelltung

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#41]
Guten Tag zusammen,

lt. der Sparda-Bank Nürnberg ist die Umsetzung von CreditLife und BaufiProtect bei Europace für Baufi Smart bis Ende 3/Anfang 4 / 2019 angekündigt. Ist das richtig?
Hier müssen wir dann klären, welche Daten gezogen/erfasst etc. und dann in der API bereitgestellt werden sollen/müssen. 
Ich kenne mich bei den Themen nur oberflächlich aus - werde mich aber hier intern schlau machen.
Vielen Dank und VG, Manuela Kränz

**Comment by caspii** [comment]
Ja, so grob stimmt das. Ein Kollege wird sich hierzu im Ticket noch mal melden

**Comment by NicoleNiemann** [comment]
Info von René Kutz zu dem Thema: Das Feature ist für die Bank freigeschaltet wird aber aufgrund fehlender Feature wohl b.a.w. nicht genutzt. Ticket kann geschlossen werden
