### ISSUE TITLE
Baufi Smart / Mandant SpBank Hessen - kein Kombidarlehen mit BSV-Tilgungsersatz annehmbar

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#42]
Hallo zusammen,
ich kann keinen Testantrag mit einem Kombinationsdarlehen und BSV Tilgunsersatz für die SpB Hessen mit meinem User manuela5.kraenz5@sdv-it.de annehmen.
Testfall: LV2608
Das Angebot ist annehmbar
Ich wähle aus:
Kontakt für Sparda-Bank Hessen eG
Kontakt für BSK Schwäbisch Hall
Weiter Angaben zum Geschäftsabschluss
Hake an:
Hiermit bestätige ich ....
Gebe mein PW ein 
Aber der Button: Angebot annehmen wird nicht aktiv 
Was ist das Problem?? Weil die Bausparkasse involviert ist? Weil nur mein User dazu nicht berechtigt ist? Oder derzeit allgemein für Hessen dazu kein Testfall angenommen werden kann?

Ich muss dringend die Produktschlüsselzuordnung im EPA für Hessen testen und komme nicht weiter. 
Mit der Bitte um Hilfe.
Danke und VG, Manuela Kränz #

**Comment by caspii** [comment]
Habe sie alle Haken gesetzt? Es sind ja 2 Haken, die gesetzt werden müssen. Ihr Nutzer hat auf jeden Fall das Recht, für die Sparda Hessen und die BSK SH einzureichen.

Wir haben allerdings im Moment das Problem, dass Bausparverträge Fehler bei der Annahme erzeugen. Dann müßten sie aber auch den Fehler sehen.

**Comment by u00kram** [comment]
\\A00Profiles\W7Profiles$\u00kram\Profile\Desktop\2019-03-19 16_07_13-Fischer1_MK.jpg

**Comment by u00kram** [comment]
Das hat wohl nicht funktioniert ... ich schicke den Screen per Mail.

**Comment by u00kram** [comment]
Auf Wunsch über Firefox getestet - gleiches Ergebnis. Alle Haken und Auswahlen getätigt - aber keine Freigabe für Annahme des Antrages...

**Comment by u00kram** [comment]
Ich habe heute nochmals Testanträge mit Kombidarlehen mit BSV-Tilgungsersatz versucht anzunehmen - keine Chance. EU5334 / T78336.
Außerdem den Testfall: QE2575 - den hat Herr Ehser von Hessen angelegt und auch schon einmal erfolgreich angenommen. Mir gelingt dies nach Testfallübernahme auf meinen User auch in dem Fall nicht. Es liegt also nicht an der Fallkonstellation oder ähnlichem, sondern wirklich an meinem User.
Bitte nochmal klären woran es liegen kann - ich muss dringend testen können.
Danke.

**Comment by caspii** [comment]
Ich weiß auch nicht weiter, morgen schaut ein Entwickler drauf

**Comment by caspii** [comment]
Hallo Frau Kränz, vermutlich liegt es daran, dass das Feld VEIN nicht ausgefüllt ist. Tragen sie bitte irgendwas in das Feld ein.

![image](https://user-images.githubusercontent.com/3215971/55544245-f5e02200-56ca-11e9-92a2-d5e0baeadac2.png)

**Comment by u00kram** [comment]
Test mit Eingabe: 123 ins Feld VEIN war erfolgreich.
Wenn vorher auch schon mal getestet. Aber nun war ich erfolgreich. Und die Übertragung hat auch funktioniert + richtigem Darlehensmapping - Erfolg auf der ganz Linie. :-)
Danke sehr!!!
