### ISSUE TITLE
bestehender BSV - Bausparkasse fehlt

### ISSUE THREAD

**Issue by danielschulz-genopace** [europace/baufismart-antraege-api#43]
bei einem bestehenden BSV einer Bausparkasse die nicht im Partnermanagement angelegt ist, liefert die API keinen Namen der Bausparkasse. 

Bsp. Aachener Bausparkasse

Eventuell Namen aus Liste in BaufiSmart verwenden?

**Comment by danielschulz-genopace** [comment]
![grafik](https://user-images.githubusercontent.com/45036361/54609228-d0a8ae00-4a52-11e9-84e9-952959fde5a9.png)

**Comment by hripp** [comment]
Erledigt.
