### ISSUE TITLE
externeVorgangsNummer zur verfügung stellen

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#47]
Die Sparda muss den Antragsteller vom Vorgang bis in den Antrag tracken. Das ist ein legitimer Use-Case im BEV Umfeld. 

Daher muss das Feld `externeVorgangsNummer` auch im Antrag abrufbar sein.

**Comment by u00kram** [comment]
Hallo Herr Wrede,
wie weit ist denn diese Umsetzung und wann können wir damit rechnen?
Auf unserer Seite haben wir das Auslesen des Feldes: externeVorgangsNummer schon eingebaut und im aktuellen Release mit ausgerollt. Wir sind also bereit.
Danke und VG, M.Kränz

**Comment by caspii** [comment]
Hallo Frau Kränz,

@K0ne ist aktuell dran und es wird heute oder morgen in Produktion sein.

**Comment by K0ne** [comment]
wurde umgesetzt:

https://europace.slack.com/archives/C31TS2CMN/p1556038523001300
