### ISSUE TITLE
Zukünftige Einnahmen bei Haushaltspositionen fehlen in der API

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#48]
Betrifft Haushaltspositionen:

- Bank- und Sparguthaben
- Wertpapiere und Aktion
- Sonstiges Vermögen

Wenn man unter Vorhaben die Verwendung der Haushaltspositionen angibt, kann man zukünftige Einnahmen erfassen. Diese werden aber über die API nicht mit ausgeliefert.

![image](https://user-images.githubusercontent.com/37293326/55729259-17684300-5a16-11e9-8d26-b4573027b333.png)

**Comment by lisascholz** [comment]
@caspii Hi Caspar, würdest Du Dir dieses Issue mal anschauen? Und wenn es keine Einwände gibt, uns das Go geben. Es hat nicht die höchste Prio. Wir würden es uns dann zu gegebener Zeit nehmen.

**Comment by caspii** [comment]
@lisascholz sehr gerne!

**Comment by NicoleNiemann** [comment]
@lisascholz Besteht die Anforderung weiterhin?

**Comment by lisascholz** [comment]
@NicoleNiemann Das ist noch aus der Genopace-Zeit. Daher weiß ich es gerade nicht.

@hripp Daniel kann ich in Github nicht finden. Würdest du für mich mal klären, ob diese Anforderung weiter besteht.

**Comment by FabianStuehler** [comment]
Hallo Lisa,
wir werden dieses Thema in V2 nicht weiter verfolgen. Daher wird dieses issue geschlossen.
