### ISSUE TITLE
Angabe Buch- und Briefgrundschuld fehlt in der API

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#49]
Man kann bei bestehenden Darlehen (sowohl bei einem bestehenden Objekt als auch beim Finanzierungsobjekt) angeben, ob es sich um eine Buch- oder eine Briefgrundschuld handelt. Diese Angabe fehlt aber beim BestehendesDarlehenDesFinanzierungsObjekts und bei BestehendesDarlehen.

**Comment by lisascholz** [comment]
![image](https://user-images.githubusercontent.com/37293326/55789562-e0983880-5aba-11e9-9bad-a76c73f3b352.png)

**Comment by lisascholz** [comment]
@caspii Hi Caspar, könntest Du Dir auch dieses Ticket anschauen und uns Rückmeldung geben, ob wir uns das nehmen können?

**Comment by caspii** [comment]
Ja. Macht fachlich sinn. Gerne könnt ihr euch das nehmen.

**Comment by oliverharendt** [comment]
@lisascholz Besteht diese Anforderung weiterhin?

**Comment by lisascholz** [comment]
@oliverharendt Das ist noch aus der Genopace-Zeit. Daher weiß ich es gerade nicht.

@hripp Daniel kann ich in Github nicht finden. Würdest du für mich mal klären, ob diese Anforderung weiter besteht.

**Comment by FabianStuehler** [comment]
Diese Anforderung wurde mit dem Release 2.2.5 umgesetzt.
