### ISSUE TITLE
Legitimationsdaten am Antragsteller werden nicht ausgeliefert

### ISSUE THREAD

**Issue by ollio** [europace/baufismart-antraege-api#5]
Laut Doku befinden sich am Antragsteller die Legitimationsdaten, diese werden nicht geliefert

**Comment by hripp** [comment]
Duplicate of https://github.com/hypoport/antraege-edge-server/pull/33

**Comment by hripp** [comment]
Duplicate of https://github.com/hypoport/antraege-edge-server/issues/32

**Comment by hripp** [comment]
Erledigt mit Release 2.9.
