### ISSUE TITLE
 neues Feld: "letzteAenderung"

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#50]
# Problem
Als Produktanbieter möchte ich wissen, wenn sich etwas an einem Antrag ändert, insbesondere, ob neue Dokumenten freigegeben wurden. Bisher muss ich pollen und zu jeden Antrag mir merken, welche Dokumente dranhängen, um ein Diff zu machen.

# Lösung
Bei der Abfrage aller Anträge muss bei jedem Antrag das Feld `letzteAenderung` ausgegeben werden. Das Feld wird akualisiert wenn:
* Dokumente freigegeben werden
* Der Status des Antrags sich ändert
* Änderung des Kreditsachbearbeiters

Zusätzlich soll es 2 neue Query-Parameter geben, um das Abrufen von geänderten Anträgen zu erleichtern:
* aenderungBis
* aenderungSeit

Zusätzlich gibt es an den Antragsdokumenten das Feld: `freigebenAm`

**Comment by K0ne** [comment]
passt meiner Meinung nach!

**Comment by caspii** [comment]
Kurzes Update zu diesem Feature. Es hat es nicht in den aktuellen "Sprint" reingeschafft, wir sind aber zuversichtlich, dass wir es nächste Woche angehen. Ich melde mich nochmal dazu hier.

**Comment by corinnefehlauer** [comment]
Nach Prüfung des Aufwandes das Bereitstellen des freigegebenAm-Datums an den Dokumenten zu implementieren wurde festgestellt, dass diese Umsetzung sehr aufwändig ist. Wie besprochen wird deshalb das freigegebenAm-Datum an den Dokumenten vorerst nicht umgesetzt.

**Comment by corinnefehlauer** [comment]
Feature ist live. Online-Dokumentation folgt noch.

Anträge in der Anträgeliste als auch in der Einzelabfrage enthalten jetzt zusätzlich das Feld "letzteAenderung" mit Datum und Zeitpunkt der letzten Änderung im Format "2019-05-28T03:17:03.848+02:00".

Zur Abfrage der Anträgeliste (URL .../antraege/) gibt es zwei neue optionale Parameter:
- "aenderungSeit" im z.B. Format "2019-05-27T10:57:45Z"
- "aenderungBis" im z.B. Format "2019-05-28T10:57:45Z"
mit denen die Liste der Anträge eingeschränkt werden kann auf Anträge die
- nach gesetztem aenderungSeit-Datum geändert wurden (wenn aenderungBis nicht gesetzt)
- vor gesetztem aenderungBis-Datum geändert wurden (wenn aenderungSeit nicht gesetzt)
- zwischen gesetzten aenderungSeit- und aenderungBis-Datum geändert wurden (wenn beide Parameter gesetzt).

die Parameter können in allen Formaten übergeben werden, in denen auch der Datums-Parameter "angenommenNach" übergeben werden kann.

**Comment by corinnefehlauer** [comment]
Dokumentation ist online
