### ISSUE TITLE
Beleihungsauslauf/wert bei mehreren Produktanbietern falsch

### ISSUE THREAD

**Issue by lisascholz** [europace/baufismart-antraege-api#52]
Beispielfall: Kombination aus DZ Hyp und Musterbank

JT5459/1/1
JT5459/1/2

Die Beleihungsrechnung auf der Oberfläche sieht folgendermaßen aus:

Über die Anträge API werden aber in beiden Fällen die Werte der Musterbank geliefert, auch im Teilantrag der DZ Hyp. Hier müssen die Werte der DZ Hyp geliefert werden.

**Comment by lisascholz** [comment]
@caspii Hallo Caspar, wir haben gerade entdeckt, dass dieser Umstand oben vorliegt. Würdest du uns das ok geben, dass wir das beheben dürfen? Danke und Gruß

**Comment by caspii** [comment]
ja, sehr gerne! @K0ne möchte den PR bekommen

**Comment by hripp** [comment]
Im Element `beleihungsRechnung` entsprechen nun die Werte für `beleihungsAuslauf` und `beleihungsWertSumme` wieder denen des entsprechenden Produktanbieters/Kreditentscheiders.
