### ISSUE TITLE
via GET Antraege sind Anträge sichtbar, auf die die verwendete Plakette keine Leserechte hat.

### ISSUE THREAD

**Issue by mrcsneuber** [europace/baufismart-antraege-api#53]
Hallo zusammen, 

wir benutzen die Plakette IQY78. 

Um alle für uns interessanten Anträge über die API auszulesen, verwenden wir ein "zweistufiges" Verfahren. 

1. Wir nutzen GET /v2/antraege um zu sehen, welche neuen Anträge für unsere Plakette vorliegen
2. Wir nutzen GET /v2/antraege/{vorgang}/{antrag}/angebot um die detaillierten Daten des Antrags einzeln abzuholen. 

Wenn wir im ersten Schritt GET /v2/antraege aufrufen, bekommen wir zum Beispiel den Antrag S18591/1/1 als vorhandenen Antrag angezeigt. 

Wenn wir dann im zweiten Schritt GET /v2/antraege/{vorgang}/{antrag}/angebot für S18591/1/1 durchführen, bekommen wir ein `forbidden`. 

Dass wir im zweiten Schritt `forbidden` erhalten, ist korrekt, da unsere Plakette IQY78 keinen Zugriff auf S18591/1/1 hat. 

Ich wundere ich nun aber, warum wir den Antrag im ersten Schritt dann als vorhandenen Antrag überhaupt dargestellt bekommen. Wäre es nicht passender, wenn S18591/1/1 bereits bei GET /v2/antraege nicht zu sehen ist, wenn wir keine Rechte für diesen Antrag haben? 

Wir konnten außerdem nachstellen, dass im Frontend in der Antragsübersicht S18591/1/1 auch sichtbar ist, dort dann aber nicht geöffnet werden kann, da wir keine Leserechte mit IQY78 haben. 

Ich frage mich nun, ob wir dieses Verhalten in unserer Anwendung abfangen sollten, oder ob ihr das als Issue seht und auf Seiten EUROAPCE an der API beheben würdet. 

Vielen Dank für eine Info. 

Beste Grüße nach Berlin, 
Marcus
axilaris

**Comment by mrcsneuber** [comment]
Hi Caspar, 

hat eure Analyse etwas ergeben? Werdet ihr das Thema zeitnah fixen können? 

VG
Marcus

**Comment by Integer93** [comment]
Works for me.
