### ISSUE TITLE
Kein Tilgungsbeitrag (BSV Tilgungsersatz) in der Anträge API Baufi Smart ??

### ISSUE THREAD

**Issue by u00kram** [europace/baufismart-antraege-api#60]
Guten Tag Herr Wrede,
Beispiel-Testfall X51382/3
Bisher wird bei der Datenbereitstellung über die Anträge API Baufi Smart für den BSV-Tilgungersatz nur der Sparbeitrag mitgegeben. Die   tilgungsPhase: null hat dann keinen "tilgungsBeitragMonatlich".
(In der Anwendung ist der Tilgungsbeitrag im Angebot mit ausgegeben und die Banken möchten ihn gern mit gemappt haben.)
So in der Version 2.12 - es gibt schone eine Version 2.13 - ist dies darin schon enthalten?
Wenn nicht - ist es möglich, den Tilgungsbeitrag als tilgungsBeitragMonatlich in die Anträge API Baufi Smart einzubauen?
Wenn die Bezeichnung so verwendet wird, können wir dies schon so in die Programmierung aufnehmen?!!  Wir bauen gerade bis Freitag eine Releaseversion.

Vielen Dank und VG, Manuela Kränz

}
                    sparPhase: class SparPhase {
                        guthabenBeiZuteilung: null
                        sparBeitragMonatlich: 119.00
                        sparPhaseInJahren: null
                    }
                    tarif: BHW WohnBausparen (FI1N)
                    tilgungsPhase: null
                    typ: BAUSPARVERTRAG
                    vertragsBeginn: 2019-06-25
                    vertragsNummer: NEUVERTRAG
                    verwaltungsgebuehrenJaehrlich: 12.00
                    zuteilungsDatum: 2029-03-01
                }]

**Comment by caspii** [comment]
Beim Request https://baufismart.api.europace.de/v2/antraege/X51382/3 über die API kommt schon `tilgungsBeitragMonatlich`. Siehe Screenshot:

![image](https://user-images.githubusercontent.com/3215971/60281772-df321b80-9905-11e9-8ce1-18973e0e2950.png)

Hier noch mal das ganze im UI
![image](https://user-images.githubusercontent.com/3215971/60281799-ebb67400-9905-11e9-8cc7-8a917c2c79c9.png)

Liegt hier ein Missverständnis vor?

**Comment by u00kram** [comment]
Hallo Herr Wrede,
danke für die Antwort. 
Ich gebe mal die Info von Herrn Tauber in meinen Wort an Sie weiter:
Leider nutzen uns diese Restclient-Experimente mit Erstellung eines Jason-Dokumentes nicht viel - dies entspricht nicht dem von uns verwendeten Java-Client-Ergebnis. Siehe mein Ausschnitt aus der Java-aufbereiteten "Response"Datei (X51382/3): (tilgungsPhase: null)

 sparPhase: class SparPhase {
 guthabenBeiZuteilung: null
 sparBeitragMonatlich: 119.00
 sparPhaseInJahren: null
 }
 tarif: BHW WohnBausparen (FI1N)
 tilgungsPhase: null
 typ: BAUSPARVERTRAG
 vertragsBeginn: 2019-06-25
 vertragsNummer: NEUVERTRAG
 verwaltungsgebuehrenJaehrlich: 12.00
 zuteilungsDatum: 2029-03-01
 }]

Herr Tauber wird sich das Thema am Mittwoch nochmal genauer anschauen.

Frage: Der tilgungsBeitragMonatlich hat also nix mit der aktuellen Version 2.13 zu tun?
Wir sind derzeit noch mit der 2.12 unterwegs.

Danke und VG, Manuela Kränz

**Comment by NicoleNiemann** [comment]
@u00kram Besteht das Fehlverhalten noch?

**Comment by u00kram** [comment]
Hallo Frau Niemann, bisher wird der Tilgungsbeitrag in der Response-Datei mit den Daten noch nicht mitgegeben. Wenn dies noch angepasst werden kann, wäre super. Bitte obige Kommunikation beachten. Wir gehen zeitnah mit neuer Schnittstelle von BaufiSmart nach (neu) Globo-ZAP live. Da können wir dann noch Anpassungen dafür machen. 
Danke und VG, Manuela Kränz

**Comment by oliverharendt** [comment]
Um es für mich nochmal festzuhalten. Das Problem besteht und ist auch nachvollziehbar. Die Herausforderung ist, dass die Sicht auf diesen Antrag für die Sparda-Bank anders ist als für die BHW. Bei dem Antrag für die Sparda-Bank (X51382/3/1) werden die von der BHW berechneten Bausparangebote als `externeBausparAngebote` am `vorhaben` geliefert. Hier fehlen dann die Daten zur Tilgungsphase. Im Gegensatz zu den `bausparvertraege`. am `angebot` bei der BHW-Sicht.

**Comment by Integer93** [comment]
@u00kram Wir Arbeiten aktuell an dem Fehlverhalten.
Welche Daten Fehlen denn? Wir würden zusätzlich folgende Daten ausgeben:
- tilgungsPhaseInJahren
- tilgungsBeitragMonatlich
- sparPhaseInJahren

**Comment by u00kram** [comment]
Hallo,
Uns ging es hauptsächlich um den Tilgungsbeitrag monatlich - aber wir nehmen auch die anderen Daten, die können schon morgen angefordert werden. 
Danke und VG, Manuela

**Comment by Integer93** [comment]
Wir haben jetzt bei uns Anpassungen vorgenommen. Seit Samstag erstellte Anträge sollten den Tilgungsbeitrag monatlich enthalten. Die anderen Daten benötigen eine größere Anpassung und werden von uns mit einer anderen Anpassung durchgeführt.

@u00kram Könntet ihr nochmal verifizieren, dass ihr bei neuen Anträgen den Tilgungsbeitrag an der API erhaltet? Falls ja könnt ihr gerne das Ticket schließen.

**Comment by u00kram** [comment]
Hallo,
danke für die Umsetzung. Der monatliche Tilgungsbeitrag beim Tilgungsersatz zum BVD wird nun in der Responsedatei mitgegeben. Das Mapping muss bei uns erst noch auf Anforderung der Bank umgesetzt werden.
Damit kann das Ticket geschlossen werden.

Antrag AK8TSE/1/1 von BW
   }
                    tarif: BHW WohnBausparen (FI2N) 0,10% | 2,35%
                    tilgungsPhase: class TilgungsPhase {
                        bausparDarlehenSumme: null
                        sollZinsNachZuteilung: null
                        tilgungsBeitragMonatlich: 1020.00
                        tilgungsPhaseInJahren: null
                    }
