### ISSUE TITLE
Ansprechpartner (Bearbeiter des Vorgangs) wird nicht zur Verfügung gestellt

### ISSUE THREAD

**Issue by Creice** [europace/baufismart-antraege-api#61]
Es wird lediglich der Kundenbetreuer des Vorgangs in der Antrags API geliefert. Das ist falsch und schlimm, weil gerade bei den Poolern immer der Bearbeiter des Vorgangs der Ansprechpartner ist. 
In diesem Zendesk Ticket wird das gut beschrieben: https://europace2.zendesk.com/agent/tickets/86965

**Comment by oliverharendt** [comment]
Da das ZenDesk-Ticket schon geschlossen ist, mach ich das hier auch mal zu.
