### ISSUE TITLE
Abruf der in BaufiSmart angebenenen Branche (Zusatzangabe) via Anträge API 

### ISSUE THREAD

**Issue by mrcsneuber** [europace/baufismart-antraege-api#64]
Hallo zusammen, 

wir versuchen gerade den Abruf der vom Vermittler getroffenen Angabe zur Branche der Antragsteller umzusetzen. Wir würden gern auf das Feld `"brancheBeiSRating"` setzen. 

In unseren auf dem Testsystem erzeugten Testanträgen erhalten wir trotz Befüllung der entsprechenden Zusatzangaben immer `"brancheBeiSRating": null`, aus der API. 

Beispielanträge sind: 
L94300/1/1
Q71830/1/1 

Ist die Übermittlung der Branche ggf. an bestimme Produktanbieter gekoppelt? Wir rufen mit der Plakette IQY78 ab 

Danke euch vorab! 

Viele Grüße
Marcus

**Comment by oliverharendt** [comment]
Hallo Marcus,
mit dem neuen [Release 2.24](https://github.com/europace/baufismart-antraege-api/releases/tag/v2.24) wird die Branche nun unter dem Attribut `branche` geliefert. Für dich wäre dabei die Branche interessant, die unter dem Typ `S_RATING` zu finden ist.

Viele Grüße
Oli
