### ISSUE TITLE
Als Produktgeber möchte ich aus den Daten des Antrags erkennen können, bei welchen Finanzierungsbausteinen es sich um Volltilger handelt.

### ISSUE THREAD

**Issue by mrcsneuber** [europace/baufismart-antraege-api#65]
Aktuell ist diese Unterscheidung nicht möglich.

**Comment by caspii** [comment]
Wird aktuell nicht gebraucht, wurde von DKB anders gelöst

**Comment by FabianStuehler** [comment]
Anhand der Eigenschaften des Darlehens lässt sich erkennen, dass es sich um einen Volltilger handeln könnte: restschuldNachZinsBindungsEnde = 0.
Dieser Wert wird auch über die AntragAPI ausgegeben.

**Comment by caspii** [comment]
@FabianStuehler ich schließe das Ticket
