### ISSUE TITLE
Als Produktgeber möchte ich bei durchgeführten KfW-Reservierungsverfahren, -Datum, -Gültigkeit und -Indentifikationsnummer per API abrufen können, um diese Daten bei der Automatisierung des eigenen Workflows ggü. der KfW verwenden zu können.

### ISSUE THREAD

**Issue by mrcsneuber** [europace/baufismart-antraege-api#66]
Die Daten sind momentan nicht per Anträge API abrufbar und müssen somit per Medienbruch vom Sachbearbeiter ermittelt werden. Ein Abruf per API würde die Darstellung im eigenen Middleoffice sowie die Ansprache der APIs der KfW deutlich vereinfachen und automatisierbar machen.

**Comment by FabianStuehler** [comment]
Baufismart hat bisher noch keine SST zur KFW BDO. Diese müsste erst entwickelt werden.

**Comment by FabianStuehler** [comment]
Ich schließe dieses issues, bis Baufismart eine Schnittstelle zur KfW integriert hat.
