### ISSUE TITLE
POST / PATCH "bearbeitungsFortschritt"

### ISSUE THREAD

**Issue by paulstegmann** [europace/baufismart-antraege-api#67]
Wir wollen die Möglichkeit haben für unsere Fälle / Anträge das Feld "bearbeitungsFortschritt" ändern zu können.

**Comment by caspii** [comment]
Hallo Paul,

der bearbeitungsFortschritt wird vom status des Antragesteller und des Produktanbieters abgeleitet

```
 "status": {
                "antragsteller": "BEANTRAGT",
                "bearbeitungsFortschritt": "NICHT_VON_PRODUKTANBIETER_BESTAETIGT",
                "produktAnbieter": "NICHT_BEARBEITET"
            },
```
er lässt sich also nicht direkt ändern.
