### ISSUE TITLE
Liste von Anträgen enthält Status & Produktanbieter

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-antraege-api#69]
Um nicht jeden Antrag explizit wegen des Status auslesen zu müssen, wird der Status mit in der Liste ausgegeben.

In gleicher Form wie im Antrag. Da es sich um den Status eines Teilantrags handelt, wird noch der Produktanbieter mit ausgegeben. In einem weiteren Release wird die komplette ANtragsnummer "AB1234/1/1" ausgegeben und nicht wie bisher die Annahmenummer "AB1234/1"

**Comment by paulstegmann** [comment]
Klingt gut - sind hier auch diese status dabei?

Beispiel:
"status": {
        "antragsteller": "UNTERSCHRIEBEN",
        "bearbeitungsFortschritt": "VON_PRODUKTANBIETER_BESTAETIGT",
        "produktAnbieter": "UNTERSCHRIEBEN"

**Comment by AndreKeil** [comment]
Schließung des Issues.

Eine Erweiterung der Listeneinträge um den Status ist nach aktueller Sachlage nicht angedacht. 

Hintergrund: Die Statusumstellung ist nur eine von vielen Änderungen am Antrag, welche im laufenden Bearbeitungsprozess eine Reaktion des API-Users, i. d. R. des Kreditentscheiders, bedürfen. Zu nennen wären beispielhaft die Freigabe von Unterlagen oder die Übermittlung von antragsrelevanten Nachrichten seitens des Vertriebs. Die alleinige Bereitstellung der Statusinformation führte daher nicht zu einer Prozessverbesserung; andererseits sind die möglichen Szenarien für einen "Blick" in den Antrag zu vielfältig, um alle erdenklichen Daten in die Liste aufzunehmen.

Ob und wann sich am Antrag etwas änderte, ist an den Feldern `letzteAenderung` und `letztesEreignis` erkennbar. Um was es sich dabei genau handelt, hierüber gibt die konkrete Antragsabfrage Auskunft.
