### ISSUE TITLE
lebenshaltungsKostenMonatlich werden nicht mit zurückgeliefert

### ISSUE THREAD

**Issue by K0ne** [europace/baufismart-antraege-api#7]
Warum ist das Feld „lebenshaltungsKostenMonatlich" für die DZ HYP nicht gefüllt?

**Comment by lisascholz** [comment]
Weil das das produzentenspezifische Eingabefeld der DSL (auch verwendet von BSH) ist. Die Lebenshaltungskosten, die für jede Haushaltsrechnung von der ME berechnet werden, werden grundsätzlich noch nicht über AnträgeAuslesen ausgeliefert.

Aus meiner Sicht könnt ihr das Ticket schließen.

**Comment by lisascholz** [comment]
Mittlerweile werden auch die angerechneten Lebenshaltungskosten mitgeliefert. Ich schließe das Ticket deshalb jetzt.

**Comment by hripp** [comment]
Wird geschlossen.
