### ISSUE TITLE
Schlechte Fehlermeldung bei updateKreditsachbearbeiter

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-antraege-api#70]
Wenn ein nicht erlaubter Kreditsachberarbeiter per `patch` gesetzt wird kommt ein 500er zurück. Damit kann der Entwickler nichts anfangen

Response:
```
{
   "traceId": "Root=1-5dcbc509-0ab68866a6595be647d8babd",
   "message": "Fehler bei einem Call ins Backend.",
   "statusMessage": "Internal Server Error",
   "statusCode": 500
}
```

Im edge-server log ist eine viel sprechenderer Fehlermeldung zu sehen:

```
loggerName: de.hypoport.ep2.partnermanagement.api.rmi.berechtigung.produktanbieter.NeuerKreditsachbearbeiterPruefer
   message: Der neue Kreditsachbearbeiter ist ungültig. Grund: Der eingeloggte Benutzer hat keine Übernahmeerlaubnis auf OrgaEinheitId=5b56f393e4b02c1f9c94b154
```

Dieser Fehler sollte auch in der API zu sehen sein

**Comment by FabianStuehler** [comment]
Die Fehlermeldung wurde angepasst: Neuer Fehlercode 422 ersetzt Fehlercode 500 bei fehlerhaften Werten bei der Aktualisierung des Kreditsachbearbeiters.
https://github.com/europace/baufismart-antraege-api/releases
