### ISSUE TITLE
Rate/-n des TA Produktes werden nicht übertragen

### ISSUE THREAD

**Issue by matthiassass** [europace/baufismart-antraege-api#71]
Bei Anträgen mit z.B. TA Bausparen ist uns aufgefallen, dass die Raten nicht übertragen werden. Bei Ansicht der Daten ohne die Filterungen durch den ObjectSerializer von Swagger wird das Feld in der API nicht ausgewiesen. 

![EP_Feature_request](https://user-images.githubusercontent.com/58980166/70997125-9731cb80-20d4-11ea-839e-4442605cf776.jpg)

Dies hat zu Folge, dass in der Sachbearbeitung manuell eingegriffen werden muss.

Eine zeitnahe Umsetzung wäre wünschenswert.

VG + Danke für die Unterstützung
Matthias Saß
Hanseatic Bank

**Comment by caspii** [comment]
Hallo @matthiassass, könntest du mir eine Antragsnummer nennen? Danke

**Comment by matthiassass** [comment]
Hallo @caspii , klar. S20NLW

**Comment by caspii** [comment]
Okay, sie haben recht: Die Sparsumme für den Antrag S20NLW/1/2 ist in der Kreditentscheidungsinformation enthalten aber nicht in der API. Das ist unschön. Wir werden das beheben, aber ich befürchte vor Februar wird das nicht umgesetzt.

**Comment by matthiassass** [comment]
Kein Problem. Februar wäre schön da wir diese Information benötigen um die Kreditentscheidung weiter zu automatisieren.

**Comment by matthiassass** [comment]
Hallo @caspii gibt es hier ggf. schonen einen Umsetzungstermin?

**Comment by caspii** [comment]
Auch hier kann @FabianStuehler auskunft geben

**Comment by matthiassass** [comment]
Hallo zusammen,

gibt es hierzu schon Neuigkeiten? @caspii

**Comment by matthiassass** [comment]
Hallo @FabianStuehler ,

gibt es hier ein Update?

**Comment by Integer93** [comment]
Wir liefern diese Daten inzwischen an der API. Wenn ein BSV als Tilgungsersatzprodukt im Vorhaben enthalten ist weisen wir an der API am `Vorhaben` das Feld `externeBausparAngebote` aus, in diesem ist der Wert `tilgungsBeitragMonatlich` enthalten.
@matthiassass Vorgänge, die ab dem 08.07 erstellt wurden, enthalten die Daten. Könntest du das nochmal überprüfen und evtl das Issue schließen?

**Comment by matthiassass** [comment]
Prüfen wir.

**Comment by matthiassass** [comment]
Hallo @Integer93 ,
ich habe folgenden Testantrag (NJ0NHP) mit einem TA-Produkt hinterlegt. In der generierten .json taucht dies aber nicht auf. Könnt ihr das einmal prüfen?

**Comment by Integer93** [comment]
Bei einem Privatdarlehen werden die Daten tatsächlich noch nicht ausgegeben. Wir haben uns bei dem Feature bisher aus Annuitätendarlehen konzentriert. Da werden wir nochmal nachbessern.

**Comment by FabianStuehler** [comment]
Bei Privatdarlehen, die ab heute (11:30) angenommen sind, werden die Raten für die Tilgungsersatzprodukte übermittelt. Zu finden sind die Informationen bei den "externeBausparAngebote".

**Comment by matthiassass** [comment]
@FabianStuehler: Retest erfolgreich. Ticket kann zu. Vielen Dank.
