### ISSUE TITLE
Dokumentation fehlerhaft: GET /v2/antraege gibt kaum details über die anträge zurück. 

### ISSUE THREAD

**Issue by dneukirchen** [europace/baufismart-antraege-api#72]
Entgegen der Doku ([https://antraege-auslesen-api-5.api-docs.io/2.14/v2/alle-antraege-abrufen](https://antraege-auslesen-api-5.api-docs.io/2.14/v2/alle-antraege-abrufen)) gibt der `GET /v2/antraege` Endpunkt kaum verwertbare Details aus. 

Es werden lediglich antragsNummer, antragsReferenz, datenKontext, letzteAenderung und zeitpunktDerAnnahme für den jeweiligen antrag zurückgegeben.

Es wäre wünschenswert, wenn die API der Doku entspräche, so dass nicht für jeden Antrag ein zusätzlicher request erforderlich ist. In jedem Fall sollte aber bis zur Umsetzung die Doku entsprechend angepasst werden.

**Comment by dneukirchen** [comment]
related https://github.com/europace/baufismart-antraege-api/issues/69

**Comment by caspii** [comment]
@ollio könntest du bitte den Code anpassen, der die Swagger/OAS generiert?
