### ISSUE TITLE
Unterschiedliche Hypothekenraten

### ISSUE THREAD

**Issue by matthiassass** [europace/baufismart-antraege-api#75]
Hallo zusammen

Wir haben Fälle in welchen uns 2 unterschiedliche Hypothekenraten im Antrag angezeigt werden z.B.

![GIT_EP](https://user-images.githubusercontent.com/58980166/73177720-fb9e6c80-410f-11ea-9ab6-a0a412a13da0.png)

Übertragen an die API wird generell die obere Rate (in diesem Beispiel 1453,92 Euro). Nach Rücksprache mit euch kann es zu unterschiedlichen Angaben kommen, wenn der VP den Fall heute in EP erfasst hat (eingereicht aber noch nicht an die HB abgesendet) und die Rate nach  Prüfung des Erstfinanzierers beispielsweise nachjustiert werden.
Hier wird die neue Rate zwar in der KI vermerkt allerdings nicht an uns übertragen und auch nicht in der HH Rechnung berücksichtigt. 

Durch die fehlerhaft übertragene Rate kann es dann zu falschen Scoringergebnis und einer falschen HH Rechnung führen.

**Comment by FabianStuehler** [comment]
Hallo Matthias,
danke für den Hinweis. Wir schauen uns an, ob wir kurzfristig das Probleme lösen können.

**Comment by matthiassass** [comment]
Hallo @FabianStuehler ,

gibt es schon eine Erkenntnis wie das Problem gelöst werden kann?

**Comment by matthiassass** [comment]
Hallo @FabianStuehler ,

gibt es hierzu schon eine Info?

**Comment by matthiassass** [comment]
Hallo @FabianStuehler ,

wie ist hier der aktuelle Stand?

**Comment by matthiassass** [comment]
@FabianStuehler : Gibt es hierzu schon ein Update?

**Comment by FabianStuehler** [comment]
Es ist nun klar was zu tun ist. Wir werden den Fix in die Entwicklung einplanen.

**Comment by FabianStuehler** [comment]
Die Änderungen wurden am Montag ausgerollt.

**Comment by matthiassass** [comment]
@FabianStuehler , klasse. Wir werden es testen.

**Comment by FabianStuehler** [comment]
Ich schließe nun diesen issue.
