### ISSUE TITLE
Swagger Files & Code Model synchronität

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-antraege-api#79]
Die aktuelle Swagger Files enthielten im Partner Model kein "_links" Attribut, obwohl es das Model im Edge Server enthält. Ausserdem fehlten im Antrag API Descriptions an folgenden Attributen.

- kreditSachbearbeiter
- vermittler
- ansprechpartner

**Comment by schmidthappens** [comment]
Änderungen sind in Version 2.17 dokumentiert.
