### ISSUE TITLE
englische Dokumentation vervollständigen oder entfernen

### ISSUE THREAD

**Issue by oliverharendt** [europace/baufismart-antraege-api#86]
Im Repository gibt es eine englische Dokumentation. Ich frage mich - Warum? 
Es gibt nirgendwo einen Hinweis darauf. Die Dokumentation ist nur in ganz wenigen Teilen auf englisch und auch veraltet. Es gibt zwar einen Hinweis darauf, dass sie nicht up to date sein muss, aber so wie es gerade ist, wirkt das total unprofessionell. 

Daher der Vorschlag diese entweder
a) komplett zu entfernen oder 
b) auf einen vernünftigen Stand zu bringen und auch zu pflegen.

**Comment by oliverharendt** [comment]
@caspii Vielleicht kannst du was dazu sagen, warum diese Doku überhaupt existiert.

**Comment by caspii** [comment]
@oliverharendt sie existiert, weil bei der HVB Anbindung eine Englische Doku gebraucht wurde. Ich habe die wichtigsten Sache übersetzt und eingecheckt, damit es nicht verloren geht.

Von mir aus kann die gelöscht werden.

**Comment by oliverharendt** [comment]
@caspii Danke dir für die Hintergrundinformationen.

**Comment by oliverharendt** [comment]
Die englische Variante wir erstmal entfernt https://github.com/hypoport/ep-api-community/issues/5#issuecomment-605946036
