### ISSUE TITLE
Element mit dem Kennzeichen "auflösen ja/nein"

### ISSUE THREAD

**Issue by ollio** [europace/baufismart-antraege-api#9]
Bei BSV sowie LV und RV gibt es im REST-Service ein Element mit dem Kennzeichen "auflösen ja/nein" und ein Element für den max. einzusetzenden Betrag. Bei allen anderen Vermögen gibt es *nur* das Element für den max. einzusetzenden Betrag.

In der GUI ist das Feld für den max. einzusetzenden Betrag allerdings *kein* (bedingtes) Pflichtfeld.

Wie ist es von der Bedienung und von der Übertragung her angedacht? Wenn man das Vermögen als aufzulösen kennzeichnet, muss dann zwingend der max. einzusetzende Betrag angegeben werden, damit Eigenkapital in die Finanzierung eingerechnet wird? Oder wird dann bei fehlendem Betrag davon ausgegangen, dass das Vermögen komplett aufgelöst und eingesetzt wird?

**Comment by ollio** [comment]
Hier folgt das API-Model leider dem UI Model.

@ptrsauer : 
Die Felder sind anscheinend redundant und es reicht den maximal einzusetzen Betrag zu füllen. In der nächsten Minor Version können die Felder entfernt werden. Technisch bricht erstmal kein Client. In den Release Notes wird ja dann stehen, dass wie der max einzusetzende Betrag zu interpretieren ist.

**Comment by ollio** [comment]
Ich habe nun verstanden, was das Problem hier ist. Leider kommt die Irritation aus der BS UI. Wenn man hier **auflösen** anwählt, dann aber den Wert aus dem Eingabefeld löscht, wird die **auflösen** Checkbox in der Kapitalrechnung ignoriert. Das ist m.E. falsch. Wenn **auflösen** gewählt ist, dann muss der Wert in das Feld:
![image](https://user-images.githubusercontent.com/570380/48402817-dbfa6e80-e72c-11e8-82e4-60d85e001ed6.png)
übernommen werden und das Feld darf nicht mehr editierbar sein.

**Comment by ollio** [comment]
https://github.com/hypoport/ep2-core/issues/822

**Comment by caspii** [comment]
Ich habe mit UX (Josi) über das Thema gesprochen. Wie es UI-Mässig gelöst wird, ist noch offfen.

Für die API fände ich es am sinnvollsten, das Feld `vermoegensEinsatz`  für RV, LV, und BSV ganz wegzulassen. BaufiSmart rechnet anscheinend eh nur mit dem maximal einzusetzender Betrag

**Comment by FabianStuehler** [comment]
Wir nehmen uns das Thema für v3 vor.
