### ISSUE TITLE
Auslesen von Anträgen

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-antraege-api#90]
Ich habe bisher immer die Vorgänge-API genutzt um Vorgangsdaten auszulesen. Hierfür habe ich die Partner-ID "**NXU76**" verwendet und den zugehörigen REST API-Key  verwendet. Das klappt auch alles ohne Probleme. Wenn ich allerdings mit derselben Partner-ID/API-Key **Anträge** auslesen möchte, kriege ich **keine Ergebnisse** zurück, lediglich eine links-Ressource wird ausgeliefert, die genau den Link enthält, den ich gerade versuche abzufragen. 

Benötige ich für die Nutzung der Antrags-API einen weiteren API-Key? Wäre in meinen Augen unsinnig, da der Zugriff auf alle anderen APIs damit ja problemlos klappt ... bzw. was genau könnte zu dem geschilderten Verhalten führen?

**Comment by FabianStuehler** [comment]
Die Antrag API gibt noch keine Anfragen zurück. Wenn man die VorgangsAPI aufruft https://api.europace2.de/v2/vorgaenge/XXXXXX/antraege und die Nummer ist eine Anfrage, dann wird kein Ergebnis zurückgeliefert. Bei Anträgen werden funktioniert die API wie dokumentiert.

**Comment by ic-hv** [comment]
Hmm, also wenn ich die von Fabian gepostete URL(https://api.europace2.de/v2/vorgaenge/XXXXXX/antraege) verwende, kriege ich tatsächlich die Anträge zurückgeliefert ... ok - damit kann ich arbeiten ...

**Comment by ic-hv** [comment]
Vielleicht wäre es ratsam im README den Part: 

> Wie bekomme ich eine Liste aller meiner Anträge?
>
> GET https://baufismart.api.europace.de/v2/antraege
>
> Diese Liste kommt seitenweise.
> Wie rufe ich einen konkreten Antrag ab?
>
> GET https://baufismart.api.europace.de/v2/antraege/AB1234/1/1

zu korrigieren - weil damit funktionierts auf jeden Fall nicht!
